version: "3"

services:

  app:

    image: nodered/node-red:2.2.3
    restart: always
    volumes:
      - "{{ basedir }}/data/:/data"
    environment:
      TZ: "Europe/Berlin"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=1880
    networks:
        - default
        - web

networks:
  web:
    external: true
