---

- name: Ensure NFS utilities are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - nfs-common

- name: Ensure directories to import exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_imports }}"

- name: Mount up devices and modify fstab 
  mount:
    path: "{{ item.strip().split()[0] }}"
    src: "{{ item.strip().split()[1] }}"
    fstype: nfs
    opts: auto,rw,sync,noatime,nfsvers=3
    state: present
  with_items: "{{ nfs_imports }}"

