---
- include: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/mysql_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/mysql_user_pass",  length: 12 }
   - { path: "{{ basedir }}/mailcow_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/watchdog_notify_mail",  length: -1 }

- name: "create folder struct for {{ servicename }}"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}/data"
    - "{{ basedir }}/data/mysql"
    - "{{ basedir }}/data/mysql-socket"
    - "{{ basedir }}/data/redis"
    - "{{ basedir }}/data/rspamd"
    - "{{ basedir }}/data/solr"
    - "{{ basedir }}/data/postfix"
    - "{{ basedir }}/data/sogo-web"
    - "{{ basedir }}/data/sogo-userdata-backup"
    - "{{ basedir }}/data/xmpp-vol-1"
    - "{{ basedir }}/data/xmpp-upload-vol-1"


- name: "create folder struct for {{ servicename }} 2"
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "5000"
    group: "5000"
    mode: "ugo+rwx"
  with_items:
  - "{{ basedir }}/data/crypt"
  - "{{ basedir }}/data/vmail"
  - "{{ basedir }}/data/vmail-index"   


- name: Git checkout mailcow
  git:
    repo: 'https://github.com/mailcow/mailcow-dockerized.git'
    dest: "{{ basedir }}/mailcow-dockerized"
    version: a5eec3569eac1ddb33375ffde5df8b868f38c908
    # current version 2021-02-22


- name: "create folder struct for {{ servicename }} 3"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}/mailcow-dockerized/data/assets/ssl/"


# DH Parameter erzeugen
- name: check if DH Params exists
  stat:
    path: "{{ basedir }}/mailcow-dockerized/data/assets/ssl/dhparams.pem"
  register: dhparams

- name: generate new DH Params
  command: "openssl dhparam -out {{ basedir }}/mailcow-dockerized/data/assets/ssl/dhparams.pem 2048"
  when: dhparams.stat.exists == False


# Copy config files
- name: deploy mailcow config
  template:
    dest:  "{{ basedir }}/{{ item }}"
    src: "{{ item }}"
    mode: 0644
  with_items:
    - mailcow-dockerized/mailcow.conf
    - mailcow-dockerized/docker-compose.override.yml
  register: config


# Start containers
- name: "stop {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}/mailcow-dockerized"
    state: absent
  when: config.changed


- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}/mailcow-dockerized"
    state: present

