---


- name: create folder struct for {{ servicename }}
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"


- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml


- name: start {{ servicename }} docker
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
