
- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "{{ basedir }}/docker-compose.yml"

- name: "start {{ servicename }} docker"
  docker_service:
    project_src: "{{ basedir }}"
    state: present
