---
- include: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/mysql_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/mysql_user_pass",  length: 24 }
   - { path: "{{ basedir }}/n8n_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/n8n_encryption_key",  length: 64 }

- name: create folder struct for {{servicename}}
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"   
    - "{{ basedir }}/db/"   

- name: create config files
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - "docker-compose.yml"

- name: start {{servicename}} docker
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
