

services:

  app:

    image: grafana/grafana:latest
    restart: always
    volumes:
      - "{{ basedir }}/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ basedir }}/provisioning/:/etc/grafana/provisioning/"
      - "{{ basedir }}/data/:/var/lib/grafana"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=3000
    networks:
        - default
        - web

networks:
  web:
    external: true
