version: "3"

services:

  app:

    image: grafana/grafana:8.3.1
    restart: always
    volumes:
      - "{{ basedir }}/config/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ basedir }}/config/ldap.toml:/etc/grafana/ldap.toml"
      - "{{ basedir }}/data/:/var/lib/grafana"
    environment:
      GF_SERVER_ROOT_URL: "https://{{ domain }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pass }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=3000
    networks:
        - default
        - web

networks:
  web:
    external: true
