---

- include: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/secret/ldap_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/secret/ldap_config_pass",  length: 24 }
   - { path: "{{ basedir }}/secret/ldap_readonly_pass",  length: 12 }

- name: "create folder struct for {{ servicename }}"
  file:
    path: "{{ basedir }}/{{ item.path }}"
    state: "directory"
    recurse: yes
  with_items:
    - { path: 'database' }
    - { path: 'config' }

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - Dockerfile 
    - syncrepl_exporter.yml 

- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
