version: '2.1'

services:


# Mariadb Version fixieren 

    mysql-mailcow:
        image: mariadb:10.5.7


# Prometheus Postfix Exporter

    postfix-exporter:
        image: unikum/postfix_exporter:latest
        depends_on: 
          - postfix-mailcow
        ports:
          - "{{ int_ip4 }}:9154:9154"
        volumes:
          - "postfix-vol-1:/var/spool/postfix:z"


# Export der Letsencrypt-Zertifikate von traefik zur Verwendung in Postfix und Dovecot 

    traefik-certdumper:
        image: humenius/traefik-certs-dumper
        network_mode: none
        command: --restart-containers mail_dovecot-mailcow_1,mail_postfix-mailcow_1,mail_nginx-mailcow_1,mail_watchdog-mailcow_1
        volumes:
          # mount the folder which contains Traefik's `acme.json' file
          - /srv/traefik/acme.json:/traefik/acme.json:ro
          # mount mailcow's SSL folder
          - ./data/assets/ssl/:/output:rw,z
          # Docker API for Container restart
          - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
          # only change this, if you're using another domain for mailcow's web frontend compared to the standard config
          - DOMAIN={{ domain }}

# Labels für traefik Konfiguration
# Der Container nginx-mailcow benötigt zusätzlich den Alias sogo, damit der Container wegfallen kann 

    nginx-mailcow:
      labels:
        - traefik.enable=true
        - traefik.http.routers.{{ servicename }}-mailcow.rule=Host(`${MAILCOW_HOSTNAME}`)
        - traefik.http.routers.{{ servicename }}-mailcow.entrypoints=websecure
        - traefik.http.services.{{ servicename }}-mailcow.loadbalancer.server.port=42012
      networks:
        mailcow-network:
          aliases:
            - nginx
            - sogo
        web:
          aliases:
            - mailcow

# Container anpassen um start zu unterbinden

    sogo-mailcow:
      image: stakater/exit-container
      restart: 'no'

    acme-mailcow:
      image: stakater/exit-container
      restart: 'no'

    solr-mailcow:
      image: stakater/exit-container
      restart: 'no'


# Externes Netzwerk 

networks:
  web:
    external: true


# Volumes auf lokale Verzeichnise umlenken

volumes:
  vmail-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/vmail"
  vmail-index-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/vmail-index"
  mysql-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/mysql"
  mysql-socket-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/mysql-socket"
  redis-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/redis"
  rspamd-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/rspamd"
  solr-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/solr"
  postfix-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/postfix"
  crypt-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/crypt"
  sogo-web-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/sogo-web"
  sogo-userdata-backup-vol-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "{{ basedir }}/data/sogo-userdata-backup"
