
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: {{ loki.server }}/api/prom/push

scrape_configs:

  - job_name: openhab-logs
    pipeline_stages:
    - docker:
    static_configs:
    - targets:
        - localhost
      labels:
        job: openhab-logs
        host: {{ inventory_hostname }}
        __path__: /openhab-logs/*log

