---

- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/wg_admin_pass",  length: 32 }
    - { path: "{{ basedir }}/wg_private_key",  length: -1 } # 'wg genkey'


- name: create folder struct for keycloak
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data"


- name: "copy {{ servicename }} config files"
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
  register: config


- name: "stop {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed


- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
