---

- name: install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - oracle-java8-jdk
    - openhab2
  notify: restart openhab

- lineinfile:
    path: /etc/default/openhab2
    regexp: '^EXTRA_JAVA_OPTS='
    line: 'EXTRA_JAVA_OPTS="-Djna.boot.library.path=/usr/lib/jni"'
  notify: restart openhab

- lineinfile:
    path: /usr/lib/systemd/system/openhab2.service
    regexp: '^User='
    line: 'User=root'
  notify: restart openhab

- lineinfile:
    path: /usr/lib/systemd/system/openhab2.service
    regexp: '^Group='
    line: 'Group=root'
  notify: restart openhab

- name: enable service
  service: name=openhab2 enabled=yes
  notify: restart openhab

- name: openhab configs
  template: src={{ item }} dest=/etc/openhab2/{{ item }} 
  with_items:
    - "items/gpio.items"
    - "items/homematic.items"
    - "items/rfswitches.items"
    - "items/yahoowheather.items"
    - "persistence/influxdb.persist"
    - "rules/rfswitches.rules"
    - "rules/tempcontrol.rules"
    - "services/addons.cfg"
    - "services/gpio.cfg"
    - "services/influxdb.cfg"
    - "services/rpircswitch.cfg"
    - "things/homematic.things"
    - "things/rfswitches.things"
    - "things/yahoowheather.things"
  notify: restart openhab
 
