version: "3"

services:

  app:

    image: grafana/loki:2.9.1
    restart: always
    command: -config.file=/etc/loki/local-config.yaml 
    ports:
      - "3100:3100"
    volumes:
      - /srv/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - /srv/loki/data:/data
    
  vector:

    image: timberio/vector:0.34.2-alpine
    restart: always
    depends_on: 
      - app
    ports:
      - "514:514/udp"
    volumes:
      - /srv/loki/vector.toml:/etc/vector/vector.toml
