# Pakete installieren
- name: openvpn installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - logrotate
    - openvpn

# Log-Verzeichnis erstellen 

- name: create folder struct for openvpn
  file:
    path: "/var/log/openvpn/"
    state: "directory"

# Konfigurationsdateien erstellen (ohne Keys)

- name: Konfigurationen (server) erstellen 
  template: src={{ inventory_hostname }}-{{ item }}.conf dest=/etc/openvpn/server/{{ item }}.conf
  with_items:
    - "{{ openvpn_server }}"
  notify: restart openvpn server
  when: openvpn_server is defined and openvpn_server > 0

- name: Konfigurationen (clients) erstellen 
  template: src={{ inventory_hostname }}-{{ item }}.conf dest=/etc/openvpn/client/{{ item }}.conf
  with_items:
    - "{{ openvpn_clients }}"
  notify: restart openvpn clients
  when: openvpn_clients is defined and openvpn_clients > 0

- name: OpenVpn LogRotate config erstellen 
  template: 
    src: logrotate 
    dest: /etc/logrotate.d/openvpn

# Enable service 

- name: enable openvpn systemd service (server) 
  systemd:
    name: "openvpn-server@{{ item }}.service"
    state: started
    enabled: True
  with_items:
    - "{{ openvpn_server }}"
  when: openvpn_server is defined and openvpn_server > 0

- name: enable openvpn systemd service (client)
  systemd:
    name: "openvpn-client@{{ item }}.service"
    state: started
    enabled: True
  with_items:
    - "{{ openvpn_clients }}"
  when: openvpn_clients is defined and openvpn_clients > 0
