
{% raw %}

groups:


- name: system

  rules:

  - alert: SCRAPE_FAIL
    expr: up < 1
    for: 1m
    labels:
      severity: high 
    annotations:
      summary: "Metric Scape is failing"

  - alert: SYS_DOWN
    expr: system_uptime < 1
    for: 1m
    labels:
      severity: high 
    annotations:
      summary: "System {{ $labels.host }} is down"

- name: memory

  rules:

  - alert: MEM_FULL
    expr: (( mem_total - mem_free ) / mem_total * 100) > 90
    for: 15m


- name: cpu

  rules:

  - alert: HIGH_CPU
    expr: cpu_usage_idle < 0.1 
    for: 15m


- name: disk

  rules:

  - alert: HIGH_DISK_IO
    expr: diskio_iops_in_progress > 10 
    for: 5m

  - alert: DISK_FULL_85P 
    expr: ( 100 * ( 1 - ( disk_free / disk_total ) ) ) > 85
      
  - alert: DISK_FULL_95P 
    expr: ( 100 * ( 1 - ( disk_free / disk_total ) ) ) > 95 
    labels:
      severity: high 
      
  - alert: DISK_FULL_IN_24H
    expr: predict_linear( disk_free[24h], 24*3600 ) < 0
    annotations:
      summary: "Disk {{ $labels.host }} / {{ $labels.path }} will be full in 24 hours"

  - alert: DISK_FULL_IN_4H
    expr: predict_linear( disk_free[4h], 4*3600 ) < 0
    labels:
      severity: high 
    annotations:
      summary: "Disk {{ $labels.host }} / {{ $labels.path }} will be full in 4 hours"


- name: rsyncbackup

  rules:

  - alert: RSYNC_BACKUP_AGE
    expr: (time()-rsyncbackup_lastbackup)/60/60 > 2
    annotations:
      summary: "RSync Backup {{ $labels.host }} / {{ $labels.rapo }} older than 2h"

  - alert: RSYNC_BACKUP_AGE_HIGH
    expr: (time()-rsyncbackup_lastbackup)/60/60 > 4
    labels:
      severity: high 
    annotations:
      summary: "RSync Backup {{ $labels.host }} / {{ $labels.repo }} older than 4h"


- name: borgbackup

  rules:

  - alert: BORG_BACKUP_AGE
    expr: (time()-borgbackup_lastbackup)/60/60 > 6
    annotations:
      summary: "Borg Backup {{ $labels.host }} / {{ $labels.repo }} older than 6h"

  - alert: BORG_BACKUP_AGE_HIGH
    expr: (time()-borgbackup_lastbackup)/60/60 > 12
    labels:
      severity: high 
    annotations:
      summary: "Borg Backup {{ $labels.host }} / {{ $labels.repo }} older than 12h"


- name: docker_running_containers

  rules:

  - alert: DOCKER_RUNNING_CONTAINERS_CONTROL
    expr: engine_daemon_container_states_containers{state="running",job="control_docker"} != 3
    annotations:
      summary: "Invalid number of containes on {{ $labels.host }} / {{ $labels.engine_daemon_container_states_containers }}"

  - alert: DOCKER_RUNNING_CONTAINERS_INTSERVER
    expr: engine_daemon_container_states_containers{state="running",job="intserver_docker"} != 12
    annotations:
      summary: "Invalid number of containes on {{ $labels.host }} / {{ $labels.engine_daemon_container_states_containers }}"

  - alert: DOCKER_RUNNING_CONTAINERS_MASTER
    expr: engine_daemon_container_states_containers{state="running",job="master_docker"} != 1
    annotations:
      summary: "Invalid number of containes on {{ $labels.host }} / {{ $labels.engine_daemon_container_states_containers }}"

  - alert: DOCKER_RUNNING_CONTAINERS_WEBSERVER1
    expr: engine_daemon_container_states_containers{state="running",job="webserver1_docker"} != 10
    annotations:
      summary: "Invalid number of containes on {{ $labels.host }} / {{ $labels.engine_daemon_container_states_containers }}"

  - alert: DOCKER_RUNNING_CONTAINERS_WEBSERVER2
    expr: engine_daemon_container_states_containers{state="running",job="webserver2_docker"} != 15
    annotations:
      summary: "Invalid number of containes on {{ $labels.host }} / {{ $labels.engine_daemon_container_states_containers }}"



{% endraw %}
