version: "3"

services:

  app:

    image: prom/prometheus:v2.19.0
    restart: always
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - "{{ basedir }}/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ basedir }}/config/alertrules.yml:/etc/prometheus/alertrules.yml"
      - "{{ basedir }}/data/:/prometheus"


  snmp_exporter:

    image: prom/snmp-exporter:v0.18.0
    restart: always
    ports:
      - 0.0.0.0:9116:9116

