version: "3"

services:

  app:

    image: prom/prometheus:v2.13.1
    restart: always
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - /srv/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/prometheus/config/alertrules.yml:/etc/prometheus/alertrules.yml
      - /srv/prometheus/data/:/prometheus


  snmp-exporter:

    image: prom/snmp-exporter:v0.15.0
    restart: always
    ports:
      - 0.0.0.0:9116:9116
