version: "3"

services:

  app:

    image: prom/prometheus:v2.19.0
    restart: always
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - "{{ basedir }}/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ basedir }}/config/alertrules.yml:/etc/prometheus/alertrules.yml"
      - "{{ basedir }}/data/:/prometheus"


  snmp_exporter:

    image: prom/snmp-exporter:v0.18.0
    restart: always
    ports:
      - 0.0.0.0:9116:9116


  edgemax_exporter:
     
    image: b3vis/edgemax_exporter
    restart: always
    ports:
      - 0.0.0.0:9132:9132
    environment:
      ARGUMENTS: "-edgemax.addr https://10.5.0.254 -edgemax.username exporter -edgemax.password {{ ubnt_exporter_pass }} -edgemax.insecure"
