
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.


scrape_configs:

{% for item in groups['server'] %}

  - job_name: '{{ item }}'

    static_configs:
      - targets: ['{{ hostvars[item]['int_ip4'] }}:9100']
        labels:
          hostname: '{{ item }}'
          group: 'server'

  {% if hostvars[item]['ldap_local']['prometheus_metrics'] is defined %}        
          
  - job_name: '{{ item }}_ldap'

    static_configs:
      - targets: ['{{ hostvars[item]['int_ip4'] }}:9328']
        labels:
          hostname: '{{ item }}'
          group: 'ldap'
  
  {% endif %}

  {% if hostvars[item]['docker']['prometheus_metrics'] is defined %}        
          
  - job_name: '{{ item }}_docker'

    static_configs:
      - targets: ['{{ hostvars[item]['int_ip4'] }}:9323']
        labels:
          hostname: '{{ item }}'
          group: 'docker'
  
  {% endif %}

  {% if hostvars[item]['docker']['prometheus_stats'] is defined %}        
          
  - job_name: '{{ item }}_dockerstats'

    static_configs:
      - targets: ['{{ hostvars[item]['int_ip4'] }}:9487']
        labels:
          hostname: '{{ item }}'
          group: 'docker'
  
  {% endif %}

{% endfor %}

  - job_name: 'postfix'

    static_configs:
      - targets: ['10.100.1.2:9154']
        labels:
          hostname: 'item'
          group: 'service'


  - job_name: 'storage'

    metrics_path: /snmp
    static_configs:
      - targets:
        - 10.5.0.100  
        labels:
          hostname: 'storage'
          group: 'network'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116

        
  - job_name: 'hpswitch'

    metrics_path: /snmp
    static_configs:
      - targets:
        - 10.5.0.253  
        labels:
          hostname: 'hpswitch'
          group: 'network'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116


  - job_name: 'firewall'

    metrics_path: /snmp
    static_configs:
      - targets:
        - 10.5.0.254  
        labels:
          hostname: 'firewall'
          group: 'network'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116


