---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/etherpad/mysql_admin_pass
  register: etherpad_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ etherpad_secrets.results | selectattr('item', 'equalto', '/data/etherpad/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 


- name: create folder struct for etherpad
  file: 
    path: "/data/etherpad/db/" 
    state: "directory"
  
- name: start mysql docker
  docker_container: 
    name: etherpad-db
    image: mariadb:10
    hostname: etherpad-db
    state: started
    restart_policy: always
    volumes:
      - /data/etherpad/db/:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: mysql
     
- name: start etherpad docker
  docker_container: 
    name: etherpad-app
    image: tvelocity/etherpad-lite:latest
    state: started
    restart_policy: always
    env: 
      ETHERPAD_TITLE: void.ms Etherpad Lite  
      ETHERPAD_PORT: 42001
    ports:
      - 127.0.0.1:42001:42001
    links:
      - etherpad-db:mysql
