---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/homegear/rfkey
  register: homegear_secrets

- name: get secrets from server 2
  set_fact: 
    rfkey: "{{ homegear_secrets.results | selectattr('item', 'equalto', '/data/homegear/rfkey') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - homegear 
    - homegear-homematicbidcos 
  notify: restart homegear

- name: enable service
  service: name=homegear enabled=yes
  notify: restart homegear

- name: disable service
  service: name=serial-getty@ttyAMA0.service enabled=no
  notify: reboot

- name: disable service
  service: name=serial-getty@serial0.service enabled=no
  notify: reboot

- name: disable service
  service: name=serial-getty@ttyS0.service enabled=no
  notify: reboot

- lineinfile:
    path: /boot/config.txt
    line: 'enable_uart=1'
  notify: reboot

- lineinfile:
    path: /boot/config.txt
    line: 'dtparam=spi=on'
  notify: reboot

- lineinfile:
    path: /boot/config.txt
    line: 'dtparam=i2c_arm=on'
  notify: reboot

- name: cmdline.txt
  template: src=cmdline.txt dest=/boot/cmdline.txt
  notify: reboot

- name: cmdline.txt
  template: src=99-com.rules dest=/etc/udev/rules.d/99-com.rules
  notify: reboot
 

- name: homematicbidcos.conf
  template: src=homematicbidcos.conf dest=/etc/homegear/families/homematicbidcos.conf
  notify: restart homegear

