---

- hosts: all 
  remote_user: root
  roles:
    - { role: roles_all/hostname, tags: hostname }
    - { role: roles_all/motd, tags: motd }
    - { role: roles_all/apt, tags: apt }
    - { role: roles_all/cronapt, tags: cronapt }
    - { role: roles_all/packages, tags: packages }
    - { role: roles_all/sshd, tags: sshd }


- hosts: infoscreen1
  remote_user: root
  roles:
    - { role: roles_infoscreen/infoscreen, tags: infoscreen }


- hosts: control 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_control/docker_openhab, tags: openhab }


- hosts: master 
  remote_user: root
  roles:
    - { role: roles_common/alerta_heartbeat, tags: alerta_heartbeat }
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_master/icinga, tags: icinga }
    - { role: roles_master/nostandby, tags: nostandby }
    - { role: roles_master/proxmox, tags: proxmox }

#    - { role: roles_master/nfsexports, tags: nfsexports }
#    - { role: roles_master/nfsimports, tags: nfsimports }


- hosts: intserver 
  remote_user: root
  roles:
    - { role: roles_common/alerta_heartbeat, tags: alerta_heartbeat }
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_influx, tags: influx_openhab, influx_instance: openhab, influx_port: 28086, chronograf_port: 28087 }
    - { role: roles_common/docker_influx, tags: influx_prometheus, influx_instance: prometheus, influx_port: 18086, chronograf_port: 18087 }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_intserver/docker_hibiscus, tags: hibiscus }
    - { role: roles_intserver/docker_loki, tags: loki }
    - { role: roles_intserver/docker_prometheus, tags: prometheus }


- hosts: webserver1,webserver2 
  remote_user: root
  roles:
    - { role: roles_common/alerta_heartbeat, tags: alerta_heartbeat }
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_webserver/nginx, tags: nginx }
    - { role: roles_webserver/docker_bind, tags: bind }
    - { role: roles_webserver/docker_ldap, tags: ldap }


- hosts: webserver1 
  remote_user: root
  roles:
    - { role: roles_webserver/docker_wordpress, tags: wordpress }
    - { role: roles_webserver/docker_nginxssh, tags: nginxssh }
    - { role: roles_webserver/docker_alerta, tags: alerta }
    - { role: roles_webserver/docker_grafana, tags: grafana }


- hosts: webserver2
  remote_user: root
  roles:
    - { role: roles_webserver/docker_commafeed, tags: commafeed }
    - { role: roles_webserver/docker_onlyoffice, tags: onlyoffice }
    - { role: roles_webserver/docker_mail, tags: mail }
    - { role: roles_webserver/docker_nextcloud, tags: nextcloud }

