---

- hosts: all 
  remote_user: root
  roles:
    - { role: roles_all/hostname, tags: hostname }
    - { role: roles_all/motd, tags: motd }
    - { role: roles_all/apt, tags: apt }
    - { role: roles_all/packages, tags: packages }
    - { role: roles_all/sshd, tags: sshd }
    - { role: roles_all/sysctl, tags: sysctl }


- hosts: infoscreen1
  remote_user: root
  roles:
    - { role: roles_infoscreen/infoscreen, tags: infoscreen }


- hosts: hpserver 
  remote_user: root
  roles:
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/cronapt, tags: cronapt }
    - { 
        role: roles_common/docker_dockerstats, tags: dockerstats, 
        servicename: dockerstats, 
        basedir: /srv/dockerstats 
      }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_hpserver/proxmox, tags: proxmox }
    - { 
        role: roles_hpserver/samba, tags: samba, 
        servicename: samba,
        basedir: /srv/samba 
      }
    - { 
        role: roles_hpserver/rsyncd, tags: rsyncd, 
        servicename: rsyncd,
        basedir: /srv/rsyncd, 
        datadir: /data/disk1/rsyncd-backup
      }


- hosts: intserver 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { 
        role: roles_common/docker_dockerstats, tags: dockerstats, 
        servicename: dockerstats, 
        basedir: /srv/dockerstats 
      }
    - { 
        role: roles_common/docker_ldap, tags: ldap, 
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap.void.ms
      }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { 
        role: roles_intserver/docker_esphome, tags: esphome,
        servicename: esphome, 
        basedir: /srv/esphome,
        web_port: 6052 
      } 
    - { role: roles_intserver/docker_hibiscus, tags: hibiscus }
    - { role: roles_intserver/docker_loki, tags: loki }
    - { role: roles_intserver/docker_mqtt, tags: mqtt }
    - { 
        role: roles_intserver/docker_unifi, tags: unifi, 
        servicename: unifi,
        basedir: /srv/unifi/
      }
    - { 
        role: roles_intserver/docker_openhab, 
        tags: openhab,
        servicename: openhab,
        basedir: /srv/openhab,
        openhab_port_http: 80,
        openhab_port_http: 443, 
        influxdb_port: 28086
      }


- hosts: webserver1,webserver2 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_webserver/docker_bind, tags: bind }
    - { 
        role: roles_common/docker_dockerstats, tags: dockerstats, 
        servicename: dockerstats, 
        basedir: /srv/dockerstats 
      }

- hosts: webserver1 
  remote_user: root
  roles:
    - { 
        role: roles_common/docker_ldap, tags: ldap,
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap.void.ms
      }
    - { 
        role: roles_common/docker_traefik, tags: traefik,
        servicename: traefik, 
        basedir: /srv/traefik,
        domain_base: "void.ms",
        domain_default: "www.void.ms"
      }
    - { 
        role: roles_webserver/docker_autodiscover, tags: autodiscover,
        servicename: autodiscover, 
        basedir: /srv/autodiscover
      }
    - { 
        role: roles_webserver/docker_grafana, tags: grafana, 
        servicename: grafana, 
        basedir: /srv/grafana, 
        domain: grafana.void.ms 
      }
    - { 
        role: roles_webserver/docker_icinga, tags: icinga, 
        servicename: icinga, 
        basedir: /srv/icinga, 
        domain: icinga.void.ms,
        api_port: 5665,
        mysql_port: 13306, 
      }


- hosts: webserver2
  remote_user: root
  roles:
    - { 
        role: roles_common/docker_ldap, tags: ldap,
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap2.void.ms
      }
    - { 
        role: roles_common/docker_traefik, tags: traefik,
        servicename: traefik, 
        basedir: /srv/traefik,
        domain_base: "void.ms",
        domain_default: "www.void.ms"
      }
    - { 
        role: roles_webserver/docker_commafeed, tags: commafeed,
        servicename: commafeed, 
        basedir: /srv/commafeed, 
        domain: commafeed.void.ms 
      }
    - { 
        role: roles_webserver/docker_invoicefetcher, tags: invoicefetcher,
        servicename: invoicefetcher, 
        basedir: /srv/invoicefetcher,
        sshport: 2222,
        mysqlport: 13306
      }
    - { 
        role: roles_webserver/docker_mail, tags: mail,
        servicename: mail, 
        basedir: /srv/mail, 
        domain: mail.void.ms, 
      }
    - { 
        role: roles_webserver/docker_nextcloud, tags: nextcloud,
        servicename: nextcloud, 
        basedir: /srv/nextcloud, 
        domain: cloud.void.ms 
      }
    - { 
        role: roles_webserver/docker_paperless, tags: paperless,
        servicename: paperless, 
        basedir: /srv/paperless,
        domain: docs.void.ms
      }
    - { 
        role: roles_webserver/docker_keycloak, tags: keycloak, 
        servicename: keycloak, 
        basedir: /srv/keycloak, 
        domain: keycloak.void.ms
      }
    - { 
        role: roles_webserver/docker_wordpress, tags: wordpress, 
        servicename: wordpress, 
        basedir: /srv/wordpress, 
        domain: www.void.ms 
      }

