---

- hosts: all 
  remote_user: root
  roles:
    - { role: roles_all/hostname, tags: hostname }
    - { role: roles_all/motd, tags: motd }
    - { role: roles_all/apt, tags: apt }
    - { role: roles_all/packages, tags: packages }
    - { role: roles_all/sshd, tags: sshd }
    - { role: roles_all/sysctl, tags: sysctl }


- hosts: infoscreen1
  remote_user: root
  roles:
    - { role: roles_infoscreen/infoscreen, tags: infoscreen }


- hosts: control 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_control/docker_openhab, tags: openhab }


- hosts: master 
  remote_user: root
  roles:
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { 
        role: roles_master/docker_volumio, tags: volumio,
        servicename: volumio, 
        basedir: /srv/volumio,
        volumioport: 3000 
      }
    - { role: roles_master/nostandby, tags: nostandby }
    - { role: roles_master/proxmox, tags: proxmox }

#    - { role: roles_master/nfsexports, tags: nfsexports }
#    - { role: roles_master/nfsimports, tags: nfsimports }


- hosts: intserver 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { 
        role: roles_common/docker_influx, tags: influx_openhab, 
        influx_instance: openhab, 
        influx_port: 28086, 
        chronograf_port: 28087 
      }
    - { 
        role: roles_common/docker_ldap, tags: ldap, 
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap.void.ms
      }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { 
        role: roles_intserver/docker_esphome, tags: esphome,
        servicename: esphome, 
        basedir: /srv/esphome,
        web_port: 6052 
      } 
    - { role: roles_intserver/docker_hibiscus, tags: hibiscus }
    - { role: roles_intserver/docker_loki, tags: loki }
    - { role: roles_intserver/docker_mqtt, tags: mqtt }
    - { 
        role: roles_intserver/docker_pihole, tags: pihole,
        servicename: pihole, 
        basedir: /srv/pihole,
        web_port: 8080 
      }
    - { 
        role: roles_intserver/docker_prometheus, tags: prometheus, 
        servicename: prometheus,
        basedir: /srv/prometheus/
      }


- hosts: webserver1,webserver2 
  remote_user: root
  roles:
    - { role: roles_common/borgbackup, tags: borgbackup }
    - { role: roles_common/cronapt, tags: cronapt }
    - { role: roles_common/docker, tags: docker }
    - { role: roles_common/docker_promtail, tags: promtail }
    - { role: roles_common/rsyncbackup, tags: rsyncbackup }
    - { role: roles_common/prometheus-node, tags: prometheus-node }
    - { role: roles_webserver/docker_bind, tags: bind }


- hosts: webserver1 
  remote_user: root
  roles:
    - { 
        role: roles_common/docker_ldap, tags: ldap,
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap.void.ms
      }
    - { 
        role: roles_common/docker_traefik, tags: traefik,
        servicename: traefik, 
        basedir: /srv/traefik
      }
    - { 
        role: roles_webserver/docker_redirectdefault, tags: redirectdefault, 
        servicename: redirectdefault, 
        basedir: /srv/redirectdefault, 
        domain: void.ms, 
        redirect-to: www.void.ms 
      }
    - { 
        role: roles_webserver/docker_wordpress, tags: wordpress, 
        servicename: wordpress, 
        basedir: /srv/wordpress, 
        domain: www.void.ms 
      }
    - { 
        role: roles_webserver/docker_nginxssh, tags: nginxssh, 
        servicename: nginxssh, 
        basedir: /srv/nginxssh_connectiv, 
        domain: connectiv.void.ms,
        sshport: 444 
      }
    - { 
        role: roles_webserver/docker_grafana, tags: grafana, 
        servicename: grafana, 
        basedir: /srv/grafana, 
        domain: grafana.void.ms 
      }
    - { 
        role: roles_webserver/docker_icinga, tags: icinga, 
        servicename: icinga, 
        basedir: /srv/icinga, 
        domain: icinga.void.ms,
        api_port: 5665,
        mysql_port: 13306, 
      }


- hosts: webserver2
  remote_user: root
  roles:
    - { 
        role: roles_common/docker_ldap, tags: ldap,
        servicename: ldap, 
        basedir: /srv/ldap, 
        domain: ldap2.void.ms
      }
    - { 
        role: roles_common/docker_traefik, tags: traefik,
        servicename: traefik, 
        basedir: /srv/traefik
      }
    - { 
        role: roles_webserver/docker_commafeed, tags: commafeed,
        servicename: commafeed, 
        basedir: /srv/commafeed, 
        domain: commafeed.void.ms 
      }
    - { 
        role: roles_webserver/docker_invoicefetcher, tags: invoicefetcher,
        servicename: invoicefetcher, 
        basedir: /srv/invoicefetcher,
        sshport: 2222,
        mysqlport: 13306
     }
    - { 
        role: roles_webserver/docker_mail, tags: mail,
        servicename: mail, 
        basedir: /srv/mail, 
        domain: mail.void.ms, 
        autoconfig: autoconfig.void.ms,
        autodiscover: autodiscover.void.ms
      }
    - { 
        role: roles_webserver/docker_nextcloud, tags: nextcloud,
        servicename: nextcloud, 
        basedir: /srv/nextcloud, 
        domain: cloud.void.ms 
      }

