
---

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ basedir }}" 
    state: "directory"

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ basedir }}/{{ item }}" 
    state: "directory"
    owner: 508
    group: 508
  with_items:
    - "data"
    - "logs"

- name: "create config files for {{ servicename }}"
  template: 
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml 
  register: config_files

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present

