version: "3"

services:

  app:

    image: prom/prometheus:v2.3.1
    restart: always
    ports:
      - 0.0.0.0:9090:9090
    volumes:
      - /srv/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/prometheus/config/alertrules.yml:/etc/prometheus/alertrules.yml
      - /srv/prometheus/data/:/prometheus


  alertmanager:

    image: prom/alertmanager:v0.15.0
    restart: always
    ports:
      - 0.0.0.0:9093:9093
    volumes:
      - /srv/prometheus/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /srv/prometheus/alert-data/:/alertmanager


  telegram:

    image: metalmatze/alertmanager-bot:0.3.1
    restart: always
    volumes:
      - /srv/prometheus/telegram-data/:/data
    environment:
      ALERTMANAGER_URL: "http://alertmanager:9093"
      LISTEN_ADDR: "0.0.0.0:8080"
      BOLT_PATH: "/data/bot.db"
      STORE: "bolt"
      TELEGRAM_ADMIN: "{{ telegram_admin }}"
      TELEGRAM_TOKEN: "{{ telegram_token }}"
