---
- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/postgres_user_pass",   length: 12 }
   - { path: "{{ basedir }}/paperless_secret_key", length: 24 }
   - { path: "{{ basedir }}/forward_auth_secret",  length: 64 }
   - { path: "{{ basedir }}/oauth_client_secret",  length: 64 }


- name: Setup OAuth Client Info 
  ansible.builtin.debug:
    msg: "Client ID: {{ servicename }} // Client Secret: {{ oauth_client_secret }} // Redirect-URI: https://{{ domain }}/_oauth" 


- name: "create folder struct for {{ servicename }}"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}/db"
    - "{{ basedir }}/data"
    - "{{ basedir }}/media"
    - "{{ basedir }}/consume"
    - "{{ basedir }}/export"


# Copy config files
- name: deploy {{ servicename }} config
  template:
    dest:  "{{ basedir }}/{{ item }}"
    src: "{{ item }}"
    mode: 0644
  with_items:
    - docker-compose.yml
  register: config


# Start containers
- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed


- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present

