---

- name: create data directory
  file: dest=/mnt/data/icinga state=directory

- name: create data directory
  file: dest=/mnt/data/icinga/status state=directory

- name: create data directory
  file: dest=/mnt/data/icinga/mysql state=directory

- name: create build directory
  file: dest=/var/lib/docker/build/icinga state=directory

- name: copy image files 
  copy: src={{ item }} dest=/var/lib/docker/build/icinga 
  with_fileglob:
    - ./*
        
- name: build docker image 
  docker_image: 
    name: icinga
    path: /var/lib/docker/build/icinga
    state: present
     
- name: start icinga image 
  docker: 
    name: icinga
    image: icinga
    state: reloaded
    restart_policy: always
    ports:
      - 0.0.0.0:3080:80
      - 0.0.0.0:5665:5665
    volumes:
      - /mnt/data/icinga/status:/var/lib/icinga2 
      - /mnt/data/icinga/mysql:/var/lib/mysql

