---
- name: create folder struct for mqtt
  file: 
    path: "/srv/mqtt/" 
    state: "directory"

- name: create folder struct for mqtt
  file: 
    path: "/srv/mqtt/data/" 
    state: "directory"
  
- name: Konfig-Dateien erstellen
  template: 
    src: "{{ item }}" 
    dest: "/srv/mqtt/{{ item }}"
  with_items:
    - docker-compose.yml

- name: start mqtt docker
  docker_service:
    project_src: /srv/mqtt/
    state: present

