---

- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/alerta/alerta_secret_key,  length: 24 }
   - { path: /srv/alerta/pushover_token,  length: -1 }
   - { path: /srv/alerta/pushover_userkey,  length: -1 }
   - { path: /srv/alerta/telegram_token,  length: -1 }
   - { path: /srv/alerta/telegram_chatid,  length: -1 }
 

- name: create folder struct for alerta
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/alerta/
    - /srv/alerta/db/


- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/alerta/{{ item }}"
  with_items:
    - docker-compose.yml
    - alertad.conf
    - config.js
    - telegram.txt
  notify: restart alerta docker

- name: start alerta docker
  docker_service:
    project_src: /srv/alerta/
    state: present
