---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /srv/wordpress/mysql_admin_pass
    - /srv/wordpress/mysql_user_pass
  register: wordpress_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ wordpress_secrets.results | selectattr('item', 'equalto', '/srv/wordpress/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    mysql_user_pass: "{{ wordpress_secrets.results | selectattr('item', 'equalto', '/srv/wordpress/mysql_user_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for wordpress
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "/srv/wordpress/"
    - "/srv/wordpress/config"
    - "/srv/wordpress/data/"
    - "/srv/wordpress/db/"

- name: create config files
  template: src={{ item }} dest=/srv/wordpress/config/{{ item }}
  with_items: 
    - uploads.ini
  register: config 

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/wordpress/docker-compose.yml"

- name: stop wordpress docker
  docker_service:
    project_src: /srv/wordpress/
    state: absent
  when: config.changed

- name: start wordpress docker
  docker_service:
    project_src: /srv/wordpress/
    state: present

