---
- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/mysql_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/mysql_user_pass",  length: 12 }

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"
    - "{{ basedir }}/db/"

- name: create config files
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items: 
    - Dockerfile
    - uploads.ini
  register: config 

- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "{{ basedir }}/docker-compose.yml"

- name: "stop {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed

- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present

