---
- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/mysql_admin_pass",  length: 24 }
   - { path: "{{ basedir }}/mysql_user_pass",  length: 12 }

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"
    - "{{ basedir }}/db/"

- name: create config files
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items: 
    - docker-compose.yml
    - uploads.ini
  register: config 

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present

