---
- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/wordpress/mysql_admin_pass,  length: 24 }
   - { path: /srv/wordpress/mysql_user_pass,  length: 12 }

- name: create folder struct for wordpress
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "/srv/wordpress/"
    - "/srv/wordpress/data/"
    - "/srv/wordpress/db/"

- name: create config files
  template: src={{ item }} dest=/srv/wordpress/{{ item }}
  with_items: 
    - Dockerfile
    - uploads.ini
  register: config 

- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/wordpress/docker-compose.yml"

- name: stop wordpress docker
  docker_service:
    project_src: /srv/wordpress/
    state: absent
  when: config.changed

- name: start wordpress docker
  docker_service:
    project_src: /srv/wordpress/
    state: present

