version: "3"

services:

  sftpserver:

    image: atmoz/sftp:alpine
    restart: always
    command: invoicefetcher:{{ sftp_user_pass }}:1001
    ports:
      - "{{ sshport }}:22"
    volumes:
      - "{{ basedir }}/upload/:/home/invoicefetcher/upload"

  uploader:

    build: .
    restart: always
    volumes:
      - "{{ basedir }}/upload/:/upload/"
    environment:
      NEXTCLOUD_USERNAME: "invoicefetcher"
      NEXTCLOUD_PASSWORD: "{{ nextcloud_user_pass }}"
      NEXTCLOUD_URL: "https://cloud.void.ms/remote.php/webdav"
      NEXTCLOUD_BASEFOLDER: "/Rechnungen"
      NEXTCLOUD_SOURCE_TAG: "Invoicefetcher-SFTP-Upload"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_USER: "rechnungen"
      MYSQL_PASS: "{{ mysql_user_pass }}"
      MYSQL_DB: "rechnungen"
      FOLDER_IN: "/upload/"
      FOLDER_PROCESSED: "/upload/processed/"
      CRON_SCHEDULE: "*/5 * * * *"

  mysql:

    image: mariadb:10.11.6
    restart: always
    ports:
      - "{{ int_ip4 }}:{{ mysqlport }}:3306"
    volumes:
      - "{{ basedir }}/db/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: "rechnungen"
      MYSQL_USER: "rechnungen"
          