---
# Pakete installieren
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /srv/librenms/mysql_admin_pass
    - /srv/librenms/mysql_user_pass
  register: librenms_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ librenms_secrets.results | selectattr('item', 'equalto', '/srv/librenms/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    mysql_user_pass: "{{ librenms_secrets.results | selectattr('item', 'equalto', '/srv/librenms/mysql_user_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for librenms
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "/srv/librenms/"
    - "/srv/librenms/db/"
    - "/srv/librenms/logs/"
    - "/srv/librenms/rrd/"

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/librenms/docker-compose.yml"

- name: start librenms docker
  docker_service:
    project_src: /srv/librenms/
    state: present
