version: "3"

services:

  db:

    image: mariadb:10.3.4
    restart: always
    volumes:
      - /srv/librenms/db/:/var/lib/mysql
      - /srv/librenms/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: librenms
      MYSQL_USER: librenms

# run database upgrades: docker exec librenms_app_1 sh -c "cd /opt/librenms && php /opt/librenms/build-base.php"
# create initial user: docker exec librenms_app_1 php /opt/librenms/adduser.php admin admin 10 test@example.com

  app:

    image: jarischaefer/docker-librenms:1.38
    restart: always
    ports:
      - 8080:80
      - 514:514
      - 514:514/udp
    volumes:
      - /srv/librenms/logs/:/opt/librenms/logs/
      - /srv/librenms/rrd/:/opt/librenms/rrd/
      - /srv/librenms/config.custom.php:/opt/librenms/conf.d/config.custom.php
    environment:
      DB_HOST: db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASS: "{{ mysql_user_pass }}"
      BASE_URL: http://10.5.0.111:8080
      TZ: Europe/Zurich
      ALERTS_ENABLE: "true"
      BILLING_CALCULATE_ENABLE: "false"
      CHECK_SERVICES_ENABLE: "true"
      DAILY_ENABLE: "true"
      DISCOVERY_ENABLE: "true"
      DISCOVERY_THREADS: 2
      POLL_BILLING_ENABLE: "true"
      POLLERS_ENABLE: "true"
      POLLERS: 4
      SNMP_SCAN_ENABLE: "true"
      SNMP_SCAN_CRON: "30 * * * *"
      ENABLE_SYSLOG: "true"
