---

- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: /srv/openhab/influxdb_password,     type: create, length: 32 }
   - { path: /srv/openhab/influxdb_token,        type: create, length: 32 }
   - { path: /srv/openhab/tradfri_code,          type: prompt }
   - { path: /srv/openhab/tradfri_code,          type: prompt }
   - { path: /srv/openhab/tradfri_identity,      type: prompt }
   - { path: /srv/openhab/tradfri_key,           type: prompt }
   - { path: /srv/openhab/location_latitude,     type: prompt }
   - { path: /srv/openhab/location_longitude,    type: prompt }
   - { path: /srv/openhab/openweathermap_apikey, type: prompt }
   - { path: /srv/openhab/pushover_token,        type: prompt }
   - { path: /srv/openhab/pushover_userkey,      type: prompt }

- name: pakete installieren
  apt:
    state: present
    name:
      - logrotate

- name: "{{ servicename }} LogRotate config erstellen"
  template: 
    src: logrotate 
    dest: /etc/logrotate.d/openhab

- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/addons/"
    - "{{ basedir }}/conf/"
    - "{{ basedir }}/conf/items/"
    - "{{ basedir }}/conf/services/"
    - "{{ basedir }}/conf/persistence/"
    - "{{ basedir }}/conf/rules/"
    - "{{ basedir }}/conf/scripts/"
    - "{{ basedir }}/conf/sitemaps/"
    - "{{ basedir }}/conf/things/"
    - "{{ basedir }}/conf/transform/"
    - "{{ basedir }}/userdata/"
    - "{{ basedir }}/influxdb-data/"
    - "{{ basedir }}/influxdb-conf/"

- name: "create {{ servicename }} config files 1"
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - promtail-config.yaml
  register: docker_config_files

- name: "create {{ servicename }} config files 2"
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - conf/items/groups.items
    - conf/items/homematic.items
    - conf/items/mqtt.items
    - conf/items/network.items
    - conf/items/other.items
    - conf/items/rfswitches.items
    - conf/items/shelly.items
    - conf/items/tradfri.items
    - conf/items/weather.items
    - conf/persistence/influxdb.persist
    - conf/persistence/rrd4j.persist
    - conf/rules/astro.rules
    - conf/rules/mainpower.rules
    - conf/rules/notifications.rules
    - conf/rules/rfswitches.rules
    - conf/rules/rfinput.rules
    - conf/rules/tvstatus.rules
    - conf/services/addons.cfg
    - conf/services/influxdb.cfg
    - conf/services/mqtt.cfg
    - conf/services/network.cfg
    - conf/services/openhabcloud.cfg
    - conf/services/runtime.cfg
    - conf/things/astro.things
    - conf/things/homematic.things
    - conf/things/mqtt.things
    - conf/things/network.things
    - conf/things/pushover.things
    - conf/things/shelly.things
    - conf/things/tradfri.things
    - conf/things/weather.things

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: docker_config_files.changed 

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present


