---
- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: "create folder struct for {{ servicename }} container"
  file: 
    path: "{{ basedir }}" 
    state: "directory"

- name: copy container files  
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items: 
    - Dockerfile
    - docker-compose.yml
    - entrypoint.sh
    - sshd_config

- name: "start {{ servicename }} docker"
  docker_service:
    project_src: "{{ basedir }}"
    state: present
