---

- name: create folder struct for mqtt
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/mqtt/
    - /srv/mqtt/data/
    - /srv/mqtt/log/

- name: create config files
  template: src={{ item }} dest=/srv/mqtt/{{ item }}
  with_items: 
    - docker-compose.yml

- name: start mqtt docker
  docker_compose:
    project_src: /srv/mqtt/
    state: present
