---

- name: install apt-transport-https packages before adding sources 
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - debian-archive-keyring
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2 
    - software-properties-common

- name: add debian repo keys 
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ debian_keys }}"
  when: debian_keys is defined and debian_keys > 0

#- name: get_docker repository key
#  shell: "curl {{ item }} | apt-key add -"
#  with_items: "{{ debian_keys }}"
#  when: debian_keys is defined and debian_keys > 0

- name: set debian repos 
  template: src=sources.list.j2 dest=/etc/apt/sources.list   

