---
# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - curl
    - logrotate

- name: create directories 
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/alerta_heartbeat 
    - /var/log/alerta_heartbeat

- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/alerta_heartbeat/alerta_api_key,  length: -1 } 

- name: Create Heartbeat Script
  template: 
    src: "{{ item }}" 
    dest: "/srv/alerta_heartbeat/{{ item }}"
    mode: u+x
  with_items:
    - "send_server_heartbeat.sh"
    - "send_service_heartbeat.sh"

- name: Create Heartbeat Cronjob
  cron: name="alerta_heartbeat" weekday="*" hour="*" minute="*" job="/srv/alerta_heartbeat/send_server_heartbeat.sh 2>&1 | ts '[\\%Y-\\%m-\\%d \\%H:\\%M:\\%S]' >> /var/log/alerta_heartbeat/send_server_heartbeat.log"
  
- name: LogRotate config erstellen 
  template: 
    src: logrotate 
    dest: /etc/logrotate.d/alerta_backup
