---
# Pakete installieren
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /srv/hibiscus/mysql_admin_pass
    - /srv/hibiscus/mysql_user_pass
  register: hibiscus_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ hibiscus_secrets.results | selectattr('item', 'equalto', '/srv/hibiscus/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    mysql_user_pass: "{{ hibiscus_secrets.results | selectattr('item', 'equalto', '/srv/hibiscus/mysql_user_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for hibiscus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/srv/hibiscus/"
    - "/srv/hibiscus/db/"

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/hibiscus/docker-compose.yml"

- name: start hibiscus docker
  community.docker.docker_compose_v2:
    project_src: /srv/hibiscus/
    state: present

