---

- name: install deb packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - docker-ce
    - python 
    - python-pip

- name: uninstall pip packages
  pip: 
    name: docker-py
    state: absent
    
- name: install pip packages
  pip: 
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: daemon config für docker erstellen 
  template: src=daemon.conf dest=/etc/docker/daemon.conf
  notify: restart docker
  