---

- name: install deb packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - docker-engine
    - python 
    - python-pip
    
- name: install pip packages
  pip: 
    name: docker-py 
    version: 1.7.2
    state: present

- name: daemon config für docker erstellen 
  template: src=daemon.conf dest=/etc/docker/daemon.conf
  notify: restart docker
  