version: "3"

services:

  ping:

    image: telegraf:1.7
    restart: always
    network_mode: host
    volumes:
      - /srv/telegraf/ping.conf:/etc/telegraf/telegraf.conf:ro

  dns:

    image: telegraf:1.7
    restart: always
    network_mode: host
    volumes:
      - /srv/telegraf/dns.conf:/etc/telegraf/telegraf.conf:ro

  {% if inventory_hostname == "intserver" %}

  firewall:

    build: .
    restart: always
    network_mode: host
    volumes:
      - /srv/telegraf/firewall.conf:/etc/telegraf/telegraf.conf:ro

  switch:

    build: .
    restart: always
    network_mode: host
    volumes:
      - /srv/telegraf/switch.conf:/etc/telegraf/telegraf.conf:ro

  storage:

    build: .
    restart: always
    network_mode: host
    volumes:
      - /srv/telegraf/storage.conf:/etc/telegraf/telegraf.conf:ro

  {% endif %}
