---

- name: create folder struct for prometheus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/db/"
    - "{{ basedir }}/config/"
    - "{{ basedir }}/data/"

- name: create config files
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/config/{{ item }}"
  with_items: 
    - prometheus.yml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "{{ basedir }}/docker-compose.yml"

- name: stop prometheus docker
  docker_service:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed

- name: start prometheus docker
  docker_service:
    project_src: "{{ basedir }}"
    state: present
