---

- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/influx_prometheus/influx_admin_pw,  length: -1 }
   - { path: /srv/prometheus/alerta_api_key,  length: -1 }
 
- name: create folder struct for prometheus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/prometheus/
    - /srv/prometheus/db/
    - /srv/prometheus/config/
    - /srv/prometheus/data/
    - /srv/prometheus/alert-data/

- name: create config files
  template: src={{ item }} dest=/srv/prometheus/config/{{ item }}
  with_items: 
    - alertmanager.yml
    - prometheus.yml
    - alertrules.yml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/prometheus/docker-compose.yml"

- name: stop prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: absent
  when: config.changed

- name: start prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: present
