---

- name: create folder struct for prometheus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/prometheus/
    - /srv/prometheus/db/
    - /srv/prometheus/config/
    - /srv/prometheus/data/

- name: create config files
  template: src={{ item }} dest=/srv/prometheus/config/{{ item }}
  with_items: 
    - prometheus.yml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/prometheus/docker-compose.yml"

- name: stop prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: absent
  when: config.changed

- name: start prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: present
