---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/seafile/mysql_admin_pass
  register: seafile_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ seafile_secrets.results | selectattr('item', 'equalto', '/data/seafile/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for seafile
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/data/seafile/"
    - "/data/seafile/data/"
    - "/data/seafile/db/"

- name: start seafile-db docker
  docker_container: 
    name: seafile-db
    image: mariadb:10
    hostname: seafile-db
    state: started
    restart_policy: always
    volumes:
      - /data/seafile/db/:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
     
- name: start seafile-app docker
  docker_container: 
    name: seafile-app
    image: foxel/seafile:6.0.6
    state: started
    restart_policy: always
    env: 
      SEAFILE_URL: https://seafile.void.ms
    ports:
      - 127.0.0.1:42003:80
    links:
      - seafile-db:mysql
    volumes:
      - /data/seafile/data/:/seafile
