---

- name: install deb packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - icinga2
    - netcat-openbsd
    - curl


- name: enable features 
  file:
   src: "/etc/icinga2/features-available/{{item}}.conf"
   dest: "/etc/icinga2/features-enabled/{{item}}.conf"
   state: link
  with_items:
    - "checker"
    - "livestatus"
    - "mainlog"
    - "notification"
  notify: restart icinga


- name: create config files 
  template: src={{ item }} dest=/etc/icinga2/conf.d/{{ item }}
  with_items:
    - "hosts.conf"
    - "pushover.conf"
    - "services.conf"
  notify: restart icinga


- name: create icinga scripts 
  template: 
    src: "{{item}}" 
    dest: "/etc/icinga2/scripts/{{item}}"
    mode: u+x
    owner: nagios
    group: nagios
  with_items:
    - "notify_by_pushover2.sh"


- name: create helper scripts
  template: 
    src: "{{item}}.sh" 
    dest: "/usr/local/bin/{{item}}"
    mode: u+x
  with_items:
    - "icinga2_status"    
