
version: "3"

services:

  openldap:
    image: osixia/openldap:1.3.0
    restart: always
    command: --loglevel debug
    hostname: {{ inventory_hostname }}-sync
    extra_hosts:
      - "webserver1-sync{% if inventory_hostname == "webserver1" %}-dummy{% endif %}:{{ hostvars['webserver1'].int_ip4 }}"
      - "webserver2-sync{% if inventory_hostname == "webserver2" %}-dummy{% endif %}:{{ hostvars['webserver2'].int_ip4 }}"
      - "intserver-sync{% if inventory_hostname == "intserver" %}-dummy{% endif %}:{{ hostvars['intserver'].int_ip4 }}"
    volumes:
      - "{{ basedir }}/database:/var/lib/ldap"
      - "{{ basedir }}/config:/etc/ldap/slapd.d"
    ports:
      - {{ int_ip4 }}:389:389
    environment:
      - HOSTNAME={{ inventory_hostname }}-sync
      - LDAP_ORGANISATION={{ ldap_global.organization }}
      - LDAP_DOMAIN={{ ldap_global.domain }}
      - LDAP_ADMIN_PASSWORD={{ ldap_admin_pass }}
      - LDAP_CONFIG_PASSWORD={{ ldap_config_pass }}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD={{ ldap_readonly_pass }}
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_REPLICATION=true
      - LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://webserver1-sync','ldap://webserver2-sync','ldap://intserver-sync']
    networks:
      - default
  
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    restart: always
    depends_on:
      - openldap
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_TRUST_PROXY_SSL=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80      
    networks:
      - default
      - web

    
networks:
  web:
    external: true    