# Loads default set of integrations. Do not remove.
default_config:

# includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:  
  name: "void-home"
  latitude: 51.961818 
  longitude: 7.624774
  elevation: 70
  unit_system: metric
  currency: EUR 
  country: DE
  time_zone: Europe/Berlin
  #internal_url: https://{{ domain }}
  internal_url: http://10.5.0.111:8123
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/22
        - 192.168.0.0/24
      allow_bypass_login: true
    - type: homeassistant

# https://www.home-assistant.io/integrations/http/
http:
  server_port: 8123
  ip_ban_enabled: False
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies: 
    - 172.0.0.0/8

# https://www.home-assistant.io/integrations/api/
api:

# https://www.home-assistant.io/integrations/logger
# log_level= critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: info
  logs:
    zigpy: info

# https://www.home-assistant.io/integrations/influxdb/
influxdb:
  api_version: 2 
  host: influxdb
  port: 8086 
  ssl: false
  organization: homeassistant
  bucket: homeassistant
  token: {{ influxdb_token }}
  default_measurement: units

# https://www.home-assistant.io/integrations/mqtt_statestream/
mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true


{% if rfswitches is defined %}

mqtt:
  switch:

# RF433 Switches
{% for device in rfswitches %}

    - object_id: {{ device.id }}
      name: {{ device.name }}
      icon: {{ device.ha_icon }}
      command_topic: "home/OpenMQTTGatewayRF433/commands/MQTTto433"
      value_template: "{% raw %}{{ value_json.value }}{% endraw %}"
      payload_on: '{"value":{{ device.code_on }},"protocol":1,"length":24,"delay":315}'
      payload_off: '{"value":{{ device.code_off }},"protocol":1,"length":24,"delay":315}'
      qos: "0"
      retain: false

{% endfor %}

{% endif %}

# Send IR Codes via Tuya ZS06 
script ansible: 

  # Turn SonyTV On or Off
  - alias: IR_SonyTV_OnOff 
    mode: single
    sequence:
      - service: zha.issue_zigbee_cluster_command
        data:
          cluster_type: in
          endpoint_id: 1
          command: 2
          ieee: 0c:ae:5f:ff:fe:92:09:ec
          command_type: server
          params:
            code: >-
              CyAJpwJpBKcCEQKnAuAHB+ADE0ALgAMBwGXg1zMDpwIRAsELAxECpwLgAwtADwERAuHZAwMRAqcC4AP34AMLBRECpwIRAg==
          cluster_id: 57348
