
version: "3"

services:

  app:

    image: linuxserver/unifi-controller:version-5.6.42
    restart: always
    volumes:
      - "{{ basedir }}/data:/config" 
    ports:
      - 3478:3478/udp #Unifi STUN port
      - 10001:10001/udp #Required for AP discovery
      - 8080:8080 #Required for device communication
      - 8443:8443 #Unifi web admin port
      #- 1900:1900/udp #Required for Make controller discoverable on L2 network option
      #- 8843:8843 #Unifi guest portal HTTPS redirect port
      #- 8880:8880 #Unifi guest portal HTTP redirect port
      #- 6789:6789 #For mobile throughput test
      #- 5514:5514 #Remote syslog port      
    environment:
      PGID: 1000
      PUID: 1000
      MEM_LIMIT: 256M
