---
- name: restart openvpn server
  service: name=openvpn-server@{{ item }}.service state=restarted
  with_items:
    - "{{ openvpn_server }}"
  when: openvpn_server is defined and openvpn_server > 0

- name: restart openvpn clients
  service: name=openvpn-client@{{ item }}.service state=restarted
  with_items:
    - "{{ openvpn_clients }}"
  when: openvpn_clients is defined and openvpn_clients > 0
