---
- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/influx/influx_admin_pw,  length: 24 }
   - { path: /srv/kapacitor/alerta_token,  length: -1 }

- name: create folder struct for kapacitor
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/kapacitor/
    - /srv/kapacitor/data/
    - /srv/kapacitor/load/
    - /srv/kapacitor/load/tasks/
    - /srv/kapacitor/load/templates/
    - /srv/kapacitor/load/handlers/


- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/kapacitor/{{ item }}"
  with_items:
    - docker-compose.yml
    - kapacitor.conf
  notify: restart kapacitor docker

- name: Script-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/kapacitor/{{ item }}"
    mode: "o+rwx"
  with_items:
    - kapacitor_listtasks.sh
    - kapacitor_show.sh
    - kapacitor_watch.sh

- name: Kapacitor-Tasks erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/kapacitor/load/tasks/{{ item }}"
  with_items:
    - task_cpu_high.tick
    - task_disk_low.tick
    - task_load1_high.tick
    - task_load5_high.tick
    - task_load15_high.tick
    - task_mem_used.tick
  notify: restart kapacitor docker 


- name: start kapacitor docker
  docker_service:
    project_src: /srv/kapacitor/
    state: present
