
version: "2"

services:
  
  app:

    image: agross/commafeed:latest
    restart: always
    mem_limit: 256m
    volumes:
      - "{{ basedir }}/config.yml:/config/config.yml"
      - "{{ basedir }}/db:/home/commafeed/"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=8082
    networks:
        - web

networks:
  web:
    external: true
