---

- name: Dist Upgrade Debian 
  apt: 
    update_cache: yes
    upgrade: dist 

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - rbp2-mediacenter-osmc
    - python-pip
    - python-crypto 
    - build-essential 
    - python-all-dev 
    - python-setuptools 
    - python-wheel 
    - python-crypto-dbg 
    - python-crypto-doc 
    - python-pip-whl

- name: install pip packages
  pip: 
    name: pycryptodomex
    state: present

- name: Symlink for Netflix add-on 
  file:
    src: /usr/lib/python2.7/dist-packages/Crypto
    dest: /usr/lib/python2.7/dist-packages/Cryptodome
    state: link

- name: download repository.netflix-1.0.1.zip
  get_url:
    url: "https://github.com/kodinerds/repo/raw/master/repository.netflix/repository.netflix-1.0.1.zip"
    dest: /home/osmc
    mode: "u=rw,g=rw,o=rw"

- name: download repository.sandmann79.plugins-1.0.2.zip
  get_url:
    url: "https://github.com/Sandmann79/xbmc/releases/download/v1.0.2/repository.sandmann79.plugins-1.0.2.zip"
    dest: /home/osmc
    mode: "u=rw,g=rw,o=rw"
