
- include_tasks: ../functions/get_secret.yml
  with_items:
  - { path: "{{ basedir }}/pihole_admin_pass", length: 12 }

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/etc-pihole/"
    - "{{ basedir }}/etc-dnsmasq.d/"

- name: "create config files"
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items: 
    - docker-compose.yml

- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
