---
# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - cron-apt

# Cron-Apt runs with default configuration 
# Daily update at 4am 
