
# Konfiguration der Platform 
esphome:
  name: test_esp8266
  platform: ESP8266
  board: d1_mini

{% include "/config/common.inc.yaml" %}

#i2c:
#  sda: 21
#  scl: 22
#  scan: True
#  id: bus_a

# IR transmitter 
#remote_transmitter:
#  pin: D1
#  carrier_duty_percent: 50%

#switch:
#  - platform: template
#    name: "Panasonic TV Off"
#    turn_on_action:
#      remote_transmitter.transmit_panasonic:
#        address: 0x4004
#        command: 0x100BCBD


# Sensor configs 
sensor:
  - platform: uptime
    name: Uptime Sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"  
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID 
