

version: "3"

services:
  

  app:

    image: jboss/keycloak:12.0.4
    restart: always
    depends_on:
      - db
    volumes:
      - /srv/keycloak/welcome-content:/opt/jboss/keycloak/welcome-content
    environment:
      KEYCLOAK_USER: "keycloakadmin"
      KEYCLOAK_PASSWORD: "{{ keycloak_admin_pass }}"
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "db"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "{{ postgres_user_pass }}"
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=8080
    networks:
      - default      
      - mail
      - web  


  db:

    image: postgres:13.2
    restart: always
    volumes:
      - /srv/keycloak/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "{{ postgres_user_pass }}" 
    networks:
      - default      


networks:
  mail:
    external: true    
  web:
    external: true    
