
- name: create folder struct for {{servicename}}
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"   

- name: create config files
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - "docker-compose.yml"
#    - "data/settings.js"

- name: start {{servicename}} docker
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
