

- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/grafana_secret_key", type: create, length: 32 }
    - { path: "{{ basedir }}/grafana_admin_pass", type: create, length: 12 }
    - { path: "{{ basedir }}/oauth_client_secret", type: create, length: 32 }

# - host: intserver
#   include_tasks: ../functions/get_secret.yml
#   with_items:
#     - { path: "/srv/homeassistant/homeassistant_influxdb_token", length: -1 }

- name: "create folder struct for {{ servicename }} 1"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"

- name: "create folder struct for {{ servicename }} 2"
  file:
    path: "{{ item }}"
    state: "directory"
    owner: 472
    group: 0
  with_items:
    - "{{ basedir }}/data/"   
    - "{{ basedir }}/provisioning/"
    - "{{ basedir }}/provisioning/datasources/"

- name: "create config files for {{ servicename }}"
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - grafana.ini
    - provisioning/datasources/datasources.yml
  register: config_files

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 


- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
