---
# Get secrets 
- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: /srv/ldap/secret/ldap_readonly_pass, length: 24 }
    - { path: /srv/grafana/grafana_admin_pass, length: 12 }


- name: create folder struct for grafana
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/srv/grafana/"
    - "/srv/grafana/config/"   
    - "/srv/grafana/data/"   

- name: create config files
  template: src={{ item }} dest=/srv/grafana/config/{{ item }}
  with_items:
    - grafana.ini
    - ldap.toml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/grafana/docker-compose.yml"

- name: start grafana docker
  docker_service:
    project_src: /srv/grafana/
    state: present
