

- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/grafana_admin_pass", length: 12 }
    - { path: "{{ basedir }}/oauth_client_secret", length: 32 }

- name: create folder struct for grafana
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"   

- name: create config filess
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - grafana.ini
  register: config_files

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 


- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
