---

- name: install collectd
  apt: pkg=collectd state=installed 
  notify:
    - restart collectd 

- name: enable collectd
  service: name=collectd enabled=yes    
  notify:
    - restart collectd 

- name: create config directory
  file: path=/etc/collectd state=directory
  notify:
    - restart collectd

- name: deploy collectd.conf 
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf 
  notify:
    - restart collectd
   
- name: deploy collection.conf
  template: src=collection.conf.j2 dest=/etc/collectd/collection.conf
  notify:
    - restart collectd

- name: deploy filters.conf
  template: src=filters.conf.j2 dest=/etc/collectd/filters.conf
  notify:
    - restart collectd

- name: deploy thresholds.conf
  template: src=thresholds.conf.j2 dest=/etc/collectd/thresholds.conf
  notify:
    - restart collectd



