---
- name: create folder struct for bind container
  file: 
    path: "{{ item }}" 
    state: "directory"
  with_items:
    - "/srv/bind/"
    - "/srv/bind/config/"

- name: Get a timestamp
  command: "date +%Y-%m-%d_%H-%m"
  register: timestamp

- name: Konfig-Dateien für bind erstellen 
  template: src={{ item }} dest=/srv/bind/config/{{ item }}
  with_items: 
    - bind.keys
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - db.root
    - db.void.ms
    - named.conf
    - named.conf.default-zones
    - named.conf.local
    - named.conf.options
    - zones.rfc1918       
  register: config 
     
- name: Docker Compose Konfig-Datei erstellen
  template: src="{{ item }}" dest="/srv/bind/{{ item }}"
  with_items:
    - "docker-compose.yml"
    - "Dockerfile"

- name: stop bind docker
  docker_service:
    project_src: /srv/bind/
    state: absent
  when: config.changed

- name: start bind docker
  docker_service:
    project_src: /srv/bind/
    state: present

