---

- name: install apt-transport-https packages before adding sources 
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - debian-archive-keyring
    - apt-transport-https

- name: add debian repo keys 
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ debian_keys }}"
  
- name: set debian repos 
  template: src=sources.list.j2 dest=/etc/apt/sources.list   

