---
- name: create folder struct for bind container
  file: 
    path: "{{ item }}" 
    state: "directory"
  with_items:
    - "/srv/bind/"
    - "/srv/bind/config/"
    - "/srv/bind/cache/"


- name: get timestamp of db.void.ms
  local_action: stat path="roles_webserver/docker_bind/templates/db.void.ms"
  register: db_void_ms


- debug: 
    msg: "db.void.ms Serial will be set to: {{ ( db_void_ms.stat.mtime | string )[:9] }} equals: {{ '%Y-%m-%d %H:%M' | strftime(db_void_ms.stat.mtime) }} UTC"


- name: Konfig-Dateien für bind erstellen 
  template: src={{ item }} dest=/srv/bind/config/{{ item }}
  with_items: 
    - bind.keys
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - db.root
    - db.void.ms
    - named.conf
    - named.conf.default-zones
    - named.conf.local
    - named.conf.options
    - zones.rfc1918       
  register: config 


- name: Docker Compose Konfig-Datei erstellen
  template: src="{{ item }}" dest="/srv/bind/{{ item }}"
  with_items:
    - "docker-compose.yml"


- name: stop bind docker
  community.docker.docker_compose_v2:
    project_src: /srv/bind/
    state: absent
  when: config.changed


- name: start bind docker
  community.docker.docker_compose_v2:
    project_src: /srv/bind/
    state: present
