---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /srv/grafana/grafana_admin_pass
  register: grafana_secrets

- name: get secrets from server 2
  set_fact: 
    grafana_admin_pass: "{{ grafana_secrets.results | selectattr('item', 'equalto', '/srv/grafana/grafana_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for grafana
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/srv/grafana/"
    - "/srv/grafana/data/"   

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/grafana/docker-compose.yml"

- name: start grafana docker
  docker_service:
    project_src: /srv/grafana/
    state: present
