version: "3"

services:

  app:

    build: .
    image: bind-app-{{ '%Y-%m-%d_%H-%M' | strftime(dockerfile.stat.mtime) }}
    restart: always
    ports:
      - 0.0.0.0:53:53
      - 0.0.0.0:53:53/udp
    volumes:
      - /srv/bind/config/:/etc/bind/
