version: "3"

services:

  app:

    image: ventz/bind:9.12.2_p1-r0
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - /srv/bind/config/:/etc/bind/
      - /srv/bind/cache/:/var/cache/bind/

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # must be a ULA range
        - subnet: fd00:dead:beef:53::/64