version: "3"

services:

  app:

    build: .
    image: bind-app-{{ timestamp.stdout }}
    restart: always
    ports:
      - 0.0.0.0:53:53
      - 0.0.0.0:53:53/udp
    volumes:
      - /srv/bind/config/:/etc/bind/
