---

- name: Add hosts file entry 
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^(.*)master.master(.*)$'
    line: "{{ int_ip4 }} master.master master pvelocalhost"

- name: Remove PVE Enterprise Repos 
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Remove conflicting Packages 
  apt: 
    state: absent
    name:
      - os-prober 
      - resolvconf 
      - rdnssd

- name: Install Proxmox Packages
  apt: 
    state: present
    name:
      - proxmox-ve 
      - nginx-light

- name: Remove PVE Enterprise Repos 
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

#- name: Subscription Popup entfernen  
#  shell: "sed -i.bak 's/NotFound/Active/g' /usr/share/perl5/PVE/API2/Subscription.pm && systemctl restart pveproxy.service" 
  
- name: Nginx Config 
  template:
    src: "nginx"
    dest: "/etc/nginx/sites-enabled/default"
  notify: restart nginx