---
- name: create folder struct for nodered
  file: 
    path: "/srv/nodered/data/" 
    state: "directory"  
     
- name: start nodered docker
  docker_container: 
    name: nodered-app
    image: nodered/node-red-docker:0.16.2
    state: started
    restart_policy: always
    volumes:
      - /srv/nodered/data/:/data
    ports:
      - 1880:1880

- name: Install NodeRed Modules
  command: docker exec nodered-app npm install {{ item }}
  with_items:
    - node-red-dashboard
    - node-red-contrib-ui
    - node-red-node-pushover

- name: Install NodeRed Modules
  command: docker restart nodered-app
    