
---

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ basedir }}" 
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data"


- name: "create config files {{ servicename }}"
  template: 
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}" 
  with_items:
    - docker-compose.yml
  register: config


- name: "stop {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}" 
    state: absent
  when: config.changed


- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}" 
    state: present

