---

- name: create folder struct for promtail
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/promtail/

- name: create config files
  template: src={{ item }} dest=/srv/promtail/{{ item }}
  with_items: 
    - docker-config.yaml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/promtail/docker-compose.yml"
  register: config_files

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
