---
- name: stop snmpd
  service: name=prometheus-node-exporter state=stopped


# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: absent
    purge: yes
  with_items:
    - prometheus-node-exporter


