---
- name: create folder struct for graphite
  file: 
    path: "{{ item }}" 
    state: "directory"  
  with_items: 
    - /srv/graphite/conf/
    - /srv/graphite/data/

- name: create config files
  template: src={{ item }} dest=/srv/graphite/conf/{{ item }}
  with_items: 
    - carbon.conf
    - blacklist.conf
    - storage-schemas.conf
    - whitelist.conf
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/graphite/docker-compose.yml"

- name: stop graphite docker
  docker_service:
    project_src: /srv/graphite/
    state: absent
  when: config.changed

- name: start graphite docker
  docker_service:
    project_src: /srv/graphite/
    state: present

