version: "2"

services:

  redis:

    image: redis:6.2.14
    restart: always
    networks:
      - default


  mysql:

    image: mariadb:10.11.5
    restart: always
    volumes:
      - "{{ basedir }}/db/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
    networks:
      - default
  

  app:

    image: nextcloud:27.1.1-apache
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - "{{ basedir }}/data/:/var/www/html/"
      - "{{ basedir }}/tmp/:/tmp/nextcloudtemp/"
      - "/srv/paperless/media/documents/archive/:/paperless-archive/:ro,z"
      - "/srv/paperless/consume/:/paperless-consume/:ro,z"
    environment:
      REDIS_HOST: "redis"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_HOST: "mysql"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_pass}}"
      OVERWRITEPROTOCOL: "https"
      OVERWRITECLIURL: "https://{{ domain }}"
      OVERWRITEHOST: "{{ domain }}"
      APPIMAGE_EXTRACT_AND_RUN: 1
      PHP_MEMORY_LIMIT: "2048M"
      PHP_UPLOAD_LIMIT: "512M"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=5368709120
      - traefik.http.middlewares.{{ servicename }}-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.{{ servicename }}.middlewares={{ servicename }}-headers,{{ servicename }}-dav
      - traefik.http.middlewares.{{ servicename }}-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - traefik.http.middlewares.{{ servicename }}-dav.replacepathregex.replacement=/remote.php/dav/"
    networks:
      - default
      - web


  webcron:
    
    image: jsonfry/curl-cron:latest 
    restart: always
    depends_on:
      - app
    environment:
      OPTIONS: "--silent http://app/cron.php"
      CRON_SCHEDULE: "*/5 * * * *"
    networks:
      - default


  # Build from Howto: https://nerdblog.steinkopf.net/2018/07/nextcloud-volltext-index-mit-docker-und-elasticsearch/
  elasticsearch:

    image: dsteinkopf/elasticsearch-ingest-attachment:latest 
    restart: always
    depends_on:
      - app
    mem_limit: 1024m
    volumes:
      - "{{ basedir }}/elasticsearch_data:/usr/share/elasticsearch/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - default


networks:
  web:
    external: true
    
