version: "3"

services:

  redis:

    image: redis:4.0.8
    restart: always

  mysql:

    image: mariadb:10.3.9
    restart: always
    volumes:
      - /srv/nextcloud/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:

    image: elberfeld/nextcloud-ocr:latest
    restart: always
    ports:
      - 127.0.0.1:42005:80
    volumes:
      - /srv/nextcloud/data/:/var/www/html/
      - /srv/nextcloud/tmp/:/tmp/nextcloudtemp/
      - /srv/nextcloud/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini:ro

  # Build from Howto: https://nerdblog.steinkopf.net/2018/07/nextcloud-volltext-index-mit-docker-und-elasticsearch/
  elasticsearch:

    image: dsteinkopf/elasticsearch-ingest-attachment:latest 
    restart: always
    volumes:
      - /srv/nextcloud/elasticsearch_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

