version: "2"

services:

  redis:

    image: redis:5.0.8
    restart: always
    networks:
      - default

  mysql:

    image: mariadb:10.4.10
    restart: always
    volumes:
      - "{{ basedir }}/db/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
    networks:
      - default
  
  app:

    image: nextcloud:18.0.2-apache
    restart: always
    volumes:
      - "{{ basedir }}/data/:/var/www/html/"
      - "{{ basedir }}/tmp/:/tmp/nextcloudtemp/"
      - "{{ basedir }}/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini:ro"
    environment:
      REDIS_HOST: "redis"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_HOST: "mysql"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_pass}}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=5368709120
    networks:
      - default
      - web

          
  # Build from Howto: https://nerdblog.steinkopf.net/2018/07/nextcloud-volltext-index-mit-docker-und-elasticsearch/
  elasticsearch:

    image: dsteinkopf/elasticsearch-ingest-attachment:latest 
    restart: always
    mem_limit: 1024m
    volumes:
      - "{{ basedir }}/elasticsearch_data:/usr/share/elasticsearch/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - default
    
networks:
  web:
    external: true
    