version: "3"

services:

  redis:

    image: redis:5.0.8
    restart: always

  mysql:

    image: mariadb:10.4.10
    restart: always
    volumes:
      - /srv/nextcloud/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:

    image: nextcloud:18.0.2-apache
    restart: always
    ports:
      - 127.0.0.1:42005:80
    volumes:
      - /srv/nextcloud/data/:/var/www/html/
      - /srv/nextcloud/tmp/:/tmp/nextcloudtemp/
      - /srv/nextcloud/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini:ro
    environment:
      REDIS_HOST: redis
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_HOST: mysql
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_pass}}"
        
  # Build from Howto: https://nerdblog.steinkopf.net/2018/07/nextcloud-volltext-index-mit-docker-und-elasticsearch/
  elasticsearch:

    image: dsteinkopf/elasticsearch-ingest-attachment:latest 
    restart: always
    volumes:
      - /srv/nextcloud/elasticsearch_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

