version: "3"

services:

  redis:

    image: redis:5.0.3
    restart: always
    volumes:
      - /srv/mail/redis:/data


  mailserver:

    build: . 
    restart: always
    domainname: void.ms   
    hostname: mail
    ports:
      - "25:25"       
      - "587:587"     
      - "993:993"     
      - "4190:4190"   
      - "127.0.0.1:42013:11334"
    environment:    
      - DBPASS=none
      - DBHOST=localhost       
      - RSPAMD_PASSWORD={{ rspamd_admin_pass }}   
      - REDIS_HOST=redis
      - DEBUG_MODE=true                        
      - ENABLE_FETCHMAIL=true                  
    volumes:
      - /srv/mail/data:/var/mail
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/mail/postfix-custom.cf:/var/mail/postfix/custom.conf:ro
      - /srv/mail/ldap_virtual_alias_maps.cf:/etc/postfix/ldap_virtual_alias_maps.cf
      - /srv/mail/ldap_virtual_domains_maps.cf:/etc/postfix/ldap_virtual_domains_maps.cf
      - /srv/mail/ldap_virtual_mailbox_maps.cf:/etc/postfix/ldap_virtual_mailbox_maps.cf
      - /srv/mail/dovecot-10-auth.conf:/etc/dovecot/conf.d/10-auth.conf
      - /srv/mail/dovecot-10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf
      - /srv/mail/dovecot-90-quota.conf:/etc/dovecot/conf.d/90-quota.conf
      - /srv/mail/dovecot-auth-ldap.conf.ext:/etc/dovecot/conf.d/auth-ldap.conf.ext
      - /srv/mail/dovecot-ldap.conf.ext:/etc/dovecot/conf.d/dovecot-ldap.conf.ext
    depends_on:
      - redis



  autodiscover:

    image: jsmitsnl/docker-email-autodiscover:release-v1.1.0
    domainname: void.ms
    restart: always
    ports:
      - 127.0.0.1:42014:80
    environment:
      COMPANY_NAME: "void.ms"
      SUPPORT_URL: "https://www.void.ms"
      DOMAIN: "void.ms"
      IMAP_HOST: "mail.void.ms"
      IMAP_PORT: "993"
      IMAP_SOCKET: "SSL"
      SMTP_HOST: "mail.void.ms"
      SMTP_PORT: "587" 
      SMTP_SOCKET: "STARTTLS"
  
