

version: "3"

services:
  

  app:

    image: jboss/keycloak:7.0.0
    restart: always
    ports:
      - 127.0.0.1:42016:8080 
    depends_on:
      - db
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "{{ keycloak_admin_pass }}"
      DB_VENDOR: "postgres"
      DB_ADDR: "db"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "{{ postgres_user_pass }}"
      PROXY_ADDRESS_FORWARDING: "true"

  db:

    image: postgres
    restart: always
    volumes:
      - /srv/keycloak/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "{{ postgres_user_pass }}" 
