---

- name: create motd file
  template: src=motd.j2 dest=/etc/motd

- name: add default repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "debian_sources"


- name: install common packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - vim
    - wget

- name: add sshkeys for server
  authorized_key: 
    user: root 
    key: "{{ lookup('file', 'keyfiles/' + item + '.pub') }}"

