---

- name: create motd file
  template: src=motd.j2 dest=/etc/motd

- name: add default repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://ftp.de.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free"
    - "deb http://ftp.de.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free"
    - "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main contrib non-free"
  when: ansible_distribution == "Debian"

- name: install common packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - vim
    - wget

- name: add sshkeys for server
  authorized_key: 
    user: root 
    key: "{{ lookup('file', 'keyfiles/' + item + '.pub') }}"

