---

- name: create folder struct for telegraf
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/telegraf/

- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/telegraf/{{ item }}"
  with_items:
    - Dockerfile
    - docker-compose.yml
  notify: restart docker_telegraf 

- name: Konfig-Dateien erstellen (intserver)
  template:
    src: "{{ item }}"
    dest: "/srv/telegraf/{{ item }}"
  with_items:
    - firewall.conf
    - storage.conf
    - switch.conf
  notify: restart docker_telegraf 

- name: Script-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/telegraf/{{ item }}"
    mode: "o+rwx"
  with_items:
    - test.sh

- name: start telegraf dockers
  docker_service:
    project_src: /srv/telegraf/
    state: present
