

version: "3"

services:
  
  app:

    image: jordan/icinga2:2.11.0
    restart: always
    ports:
      - 127.0.0.1:42017:80
      - 0.0.0.0:5665:5665
    volumes:
      - /srv/icinga/data:/var/lib/icinga2
      - /srv/icinga/etc/locale.gen:/etc/locale.gen
      - /srv/icinga/etc/icinga:/etc/icinga2
      - /srv/icinga/etc/icingaweb2:/etc/icingaweb2
      - /srv/icinga/log/apache2:/var/log/apache2
      - /srv/icinga/log/icinga2:/var/log/icinga2
      - /srv/icinga/log/icingaweb2:/var/log/icingaweb2
    depends_on:
      - db
    environment:
      APACHE2_HTTP: BOTH
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: icinga
      MYSQL_USER: icinga
      DEFAULT_MYSQL_HOST: db
      DEFAULT_MYSQL_USER: icinga
      DEFAULT_MYSQL_PASS: "{{ mysql_user_pass }}"
      ICINGAWEB2_ADMIN_PASS: "{{ icinga_admin_pass }}"
      ICINGA2_FEATURE_GRAPHITE: 1
      ICINGA2_FEATURE_GRAPHITE_HOST: graphite
      ICINGA2_FEATURE_GRAPHITE_PORT: 2003
      ICINGA2_FEATURE_DIRECTOR: 0

  db:

    image: mariadb:10.1.44
    restart: always
    volumes:
      - /srv/icinga/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: icinga
      MYSQL_USER: icinga

  graphite:
    
    image: graphiteapp/graphite-statsd:1.1.6-1
    restart: always
    volumes:
      - /srv/icinga/graphite-conf:/opt/graphite/conf
      - /srv/icinga/graphite-storage:/opt/graphite/storage
    environment:
      GRAPHITE_TIME_ZONE: "Europe/Berlin"
      GRAPHITE_DATE_FORMAT: "%d.%m.%y"
      GRAPHITE_LOG_FILE_INFO: "-"
      GRAPHITE_LOG_FILE_EXCEPTION: "-"
      GRAPHITE_LOG_FILE_CACHE: "-"
      GRAPHITE_LOG_FILE_RENDERING: "-"
