---

- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/prometheus/influx_admin_pw,  length: 24 }
   - { path: /srv/prometheus/influx_user_pw, length: 12 }
   - { path: /srv/prometheus/smtp_email_from, length: -1 }
   - { path: /srv/prometheus/smtp_auth_username, length: -1 }
   - { path: /srv/prometheus/smtp_auth_password, length: -1 }
   - { path: /srv/prometheus/alert_email_to, length: -1 }
   - { path: /srv/prometheus/pushover_user_key, length: -1 }
   - { path: /srv/prometheus/pushover_token, length: -1 }
 
 
- name: create folder struct for prometheus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/prometheus/
    - /srv/prometheus/db/
    - /srv/prometheus/config/
    - /srv/prometheus/data/
    - /srv/prometheus/alert-data/

- name: create config files
  template: src={{ item }} dest=/srv/prometheus/config/{{ item }}
  with_items: 
    - alertmanager.yml
    - prometheus.yml
    - alertrules.yml
  register: config

- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/prometheus/docker-compose.yml"

- name: stop prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: absent
  when: config.changed

- name: start prometheus docker
  docker_service:
    project_src: /srv/prometheus/
    state: present
