version: "3"

services:

  db:

    image: influxdb:1.7.8
    restart: always
    ports:
      - {{ int_ip4 }}:{{ influx_port }}:8086
    volumes:
      - /srv/influx_{{ influx_instance }}/db_data/:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "influx"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "{{ influx_admin_pw }}"
      INFLUXDB_USER: "{{influxdb_sysmon.user}}"
      INFLUXDB_USER_PASSWORD: "{{influxdb_sysmon.password}}"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"

# Only for debugging
#
#  chronograf:
#
#    image: chronograf:1.6
#    restart: always
#    volumes:
#      - /srv/influx_{{ influx_instance }}/chronograf_data/:/var/lib/chronograf
#    ports:
#      - {{ int_ip4 }}:{{ chronograf_port }}:8888
#    environment:
#      INFLUXDB_URL: "http://db:8086"
#      INFLUXDB_USERNAME: "admin"
#      INFLUXDB_PASSWORD: "{{ influx_admin_pw }}"
#      LOG_LEVEL: "info"
