---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/homegear/rfkey
  register: homegear_secrets

- name: get secrets from server 2
  set_fact: 
    rfkey: "{{ homegear_secrets.results | selectattr('item', 'equalto', '/data/homegear/rfkey') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - homegear 
    - homegear-homematicbidcos 
  notify: restart homegear

- name: enable service
  service: name=homegear enabled=yes

- name: main.conf
  template: src=main.conf dest=/etc/homegear/main.conf
  notify: restart homegear
 
- name: homematicbidcos.conf
  template: src=homematicbidcos.conf dest=/etc/homegear/families/homematicbidcos.conf
  notify: restart homegear

