---
version: "2.1"

services:

  app:
    image: lscr.io/linuxserver/heimdall:2021.11.28
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "{{ basedir }}/config:/config"
    ports:
      - "{{ heimdall_port }}:80"
