---
# Pakete installieren
- name: pakete installieren
  apt:
    update_cache: no
    state: present
    name:
      - curl


- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/nextcloud_admin_pass",  length: 32 }
    - { path: "{{ basedir }}/nextcloud_oidc_secret",  length: 32 }
    - { path: "{{ basedir }}/mysql_admin_pass",  length: 32 }
    - { path: "{{ basedir }}/mysql_user_pass",  length: 24 }
    - { path: "{{ basedir }}/smtp_user_pass",  length: -1 }


- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"
    - "{{ basedir }}/data/config"
    - "{{ basedir }}/tmp/"


- name: "create folder struct for {{ servicename }} (db)"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: 999
    group: 999
  with_items:
    - "{{ basedir }}/db/"


- name: "create folder struct for {{ servicename }} (paperless)"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: 1000
    group: 1000
  with_items:
    - "/srv/paperless/"
    - "/srv/paperless/media/"
    - "/srv/paperless/media/documents/"
    - "/srv/paperless/media/documents/archive/"


- name: Docker Compose Konfig-Datei erstellen
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - "docker-compose.yml"


- name: Nextcloud Konfig-Dateien erstellen
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/data/config/{{ item }}"
  with_items:
    - "custom.config.php"
    - "oidc.config.php"


- name: Script Helper erstellen
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
    mode: u+x
  with_items:
    - "occ.sh"


- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
