---
# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - curl

- include: ../functions/get_secret.yml
  with_items:
   - { path: /srv/nextcloud/mysql_admin_pass,  length: 24 }
   - { path: /srv/nextcloud/mysql_user_pass,  length: 12 }

- name: create folder struct for nextcloud
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: root
  with_items:
    - "/srv/nextcloud/"
    - "/srv/nextcloud/data/"
    - "/srv/nextcloud/db/"
    - "/srv/nextcloud/tmp/"
    - "/srv/nextcloud/elasticsearch_data/"

- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: set vm.max_map_count for elasticsearch etc.
  sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_file: /etc/sysctl.d/90-dstk-max_map_count.conf

- name: Docker Compose Konfig-Datei erstellen
  template: src="{{ item }}" dest="/srv/nextcloud/{{ item }}"
  with_items:
    - "docker-compose.yml"
    - "memory-limit.ini"
    - "Dockerfile-elasticsearch"
    - "Dockerfile-nextcloud"

- name: Script Helper erstellen
  template: 
    src: "{{ item }}" 
    dest: "/srv/nextcloud/{{ item }}"
    mode: u+x
  with_items:
    - "occ.sh"
    - "nextcloud-index-worker.sh"

- name: start nextcloud docker
  docker_compose:
    project_src: /srv/nextcloud/
    state: present

- name: Cronjob für nextcloud cron
  cron: name="nextcloud-cron" weekday="*" hour="*" minute="*/15" job="curl --silent http://127.0.0.1:42005/cron.php"

- name: Fulltext Worker Systemd Unit 
  template: src="{{ item }}" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - "nextcloud-index-worker.service"
#  notify: Fulltext Worker restart

- name: Fulltext Worker enableld (currently disabled) 
  systemd:
    name: nextcloud-index-worker
    daemon_reload: yes
    enabled: no

- name: Fulltext Worker start (currently disabled) 
  service:
    name: nextcloud-index-worker
    state: stopped
