---
# Pakete installieren
- name: pakete installieren
  apt:
    update_cache: no
    state: present
    name:
      - curl

- include: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/nextcloud_admin_pass",  length: 24 }
    - { path: "{{ basedir }}/mysql_admin_pass",  length: 24 }
    - { path: "{{ basedir }}/mysql_user_pass",  length: 12 }

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: root
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"
    - "{{ basedir }}/db/"
    - "{{ basedir }}/tmp/"
    - "{{ basedir }}/elasticsearch_data/"
    - "/srv/paperless/"
    - "/srv/paperless/media/"
    - "/srv/paperless/media/documents/"
    - "/srv/paperless/media/documents/archive/"

- name: Get a timestamp
  command: "date +%Y%m%d%H%M%S"
  register: timestamp

- name: set vm.max_map_count for elasticsearch etc.
  sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_file: /etc/sysctl.d/90-dstk-max_map_count.conf

- name: Docker Compose Konfig-Datei erstellen
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - "docker-compose.yml"

- name: Script Helper erstellen
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
    mode: u+x
  with_items:
    - "occ.sh"
    - "nextcloud-index-worker.sh"

- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: /srv/nextcloud/
    state: present

- name: Fulltext Worker Systemd Unit 
  template: src="{{ item }}" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - "nextcloud-index-worker.service"
#  notify: Fulltext Worker restart

- name: Fulltext Worker enableld (currently disabled) 
  systemd:
    name: nextcloud-index-worker
    daemon_reload: yes
    enabled: no

- name: Fulltext Worker start (currently disabled) 
  service:
    name: nextcloud-index-worker
    state: stopped
