---
# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - curl

- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /srv/nextcloud/mysql_admin_pass
    - /srv/nextcloud/mysql_user_pass
  register: nextcloud_secrets

- name: get secrets from server 2
  set_fact: 
    mysql_admin_pass: "{{ nextcloud_secrets.results | selectattr('item', 'equalto', '/srv/nextcloud/mysql_admin_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    mysql_user_pass: "{{ nextcloud_secrets.results | selectattr('item', 'equalto', '/srv/nextcloud/mysql_user_pass') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for nextcloud
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: www-data
    group: www-data
  with_items:
    - "/srv/nextcloud/"
    - "/srv/nextcloud/data/"
    - "/srv/nextcloud/db/"
    - "/srv/nextcloud/tmp/"
    - "/srv/nextcloud/docker_ocr/"

- name: create folder struct for nextcloud 2
  file: 
    path: "{{ item }}"
    state: "directory"
    owner: 8983
    group: 8983
  with_items:
    - "/srv/nextcloud/solr/"

- name: clone nextcloud-ocr repo
  git: 
    repo: "https://github.com/janis91/ocr.git" 
    version: "9809131759f265929085c04ed3e120241ce519dd"
    dest: "/srv/nextcloud/docker_ocr/" 
    force: "yes"
  register: gitclone_ocr 

- name: clone repo status 
  debug: 
    msg: "{{gitclone_ocr}}"
  

- name: Docker Compose Konfig-Datei erstellen
  template: src="{{ item }}" dest="/srv/nextcloud/{{ item }}"
  with_items:
    - "docker-compose.yml"

- name: start nextcloud docker
  docker_service:
    project_src: /srv/nextcloud/
    state: present

- name: Cronjob für nextcloud cron
  cron: name="nextcloud-cron" weekday="*" hour="*" minute="*/15" job=" curl --silent http://127.0.0.1:42005/cron.php"
