---

- name: "create folder struct for {{ servicename}}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/db/"

- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - database_shell.sh
    - docker-compose.yml
    - config.yml
  notify: "restart {{ servicename }} docker"

- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present
