---

- name: create folder struct for onlyoffice
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/srv/onlyoffice/"
    - "/srv/onlyoffice/cache/"
    - "/srv/onlyoffice/db/"
    
- name: Docker Compose Konfig-Datei erstellen
  template:
    src: "docker-compose.yml"
    dest: "/srv/onlyoffice/docker-compose.yml"

- name: start onlyoffice docker
  docker_service:
    project_src: /srv/onlyoffice/
    state: present
