---

- include: ../functions/get_secret.yml
  with_items:
   - { path: "/srv/influx_{{ influx_instance }}/influx_admin_pw",  length: 24 }


- name: create folder struct for influx {{ influx_instance }}
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/srv/influx_{{ influx_instance }}"
    - "/srv/influx_{{ influx_instance }}/db_data/"


- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/influx_{{ influx_instance }}/{{ item }}"
  with_items:
    - docker-compose.yml


- name: start influx {{ influx_instance }} docker
  docker_compose:
    project_src: /srv/influx_{{ influx_instance }}/
    state: present
