---

- name: install deb packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - docker-ce
    - python 
    - python-pip

- name: uninstall pip packages
  pip: 
    name: docker-py
    state: absent
    
- name: install pip packages
  pip: 
    name: "{{ item }}"
    state: present
  with_items:
    - setuptools
    - docker
    - docker-compose

- name: daemon config für docker erstellen 
  template: src=daemon.conf dest=/etc/docker/daemon.conf
  notify: restart docker

- name: daemon config für docker erstellen 
  template: 
    src: "{{item}}.sh" 
    dest: "/usr/local/bin/{{item}}"
    mode: u+x
  with_items:
    - "dc"

- name: Cronjob to prune unused images  
  cron: name="docker-prune" weekday="*" hour="5" minute="5" job="/usr/bin/docker system prune --all -f"  

- name: create telegraf config  
  template: src=telegraf.conf dest=/etc/telegraf/telegraf.d/docker.conf
  notify: restart telegraf

- name: adding existing user 'telegraf' to group docker
  user:
    name: telegraf
    groups: docker
    append: yes