---

- name: install deb packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
    install_recommends: no
  with_items:
    - docker-ce
    - python 
    - python-pip
    - python-docker

- name: install pip packages
  pip: 
    name: "{{ item }}"
    state: present
  with_items:
    - docker-compose==1.23.2
   
- name: daemon config für docker erstellen 
  template: src=daemon.json dest=/etc/docker/daemon.json
  notify: restart docker

- name: daemon config für docker erstellen 
  template: 
    src: "{{item}}.sh" 
    dest: "/usr/local/bin/{{item}}"
    mode: u+x
  with_items:
    - "dc"

- name: Cronjob to prune unused images  
  cron: name="docker-prune" weekday="*" hour="5" minute="5" job="/usr/bin/docker system prune --all -f"  

- name: "Set Docker Server Blocker file: {{ docker.service_blocker_file }}"
  ini_file:
    path: "{{ item }}"
    section: Unit
    option: ConditionFileNotEmpty
    value: "{{ docker.service_blocker_file }}"
    backup: yes
  with_items: 
    - /lib/systemd/system/containerd.service 
    - /lib/systemd/system/docker.service 
    - /lib/systemd/system/docker.socket
  when: docker.service_blocker_file is defined 

- name: force systemd to reread configs 
  systemd:
    daemon_reload: yes
