---
- name: stop snmpd
  service: name=snmpd state=stopped


# Pakete installieren
- name: pakete installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: absent
    purge: yes
  with_items:
    - snmpd

- name: delete config file
  file: 
    path: "/etc/snmp/snmpd.conf"
    state: absent

