

version: "3"

services:
  
  app:

    image: alerta/alerta-web:6.7.5
    restart: always
    ports:
      - 127.0.0.1:42010:8080
    volumes:
      - /srv/alerta/alertad.conf:/app/alertad.conf
      - /srv/alerta/telegram.txt:/app/telegram.txt
      - /srv/alerta/config.js:/web/config.js
    depends_on:
      - db
    environment:
      INSTALL_PLUGINS: "normalise,pushover,telegram"


  db:

    # TODO: Upgrade Vorgehensweise auf 11.x noch ungeklärt 
    image: postgres:10.5
    restart: always
    volumes:
      - /srv/alerta/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alerta
      POSTGRES_USER: alerta
      POSTGRES_PASSWORD: alerta 
