---

- name: "create folder struct for {{ servicename }}"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"


- name: deploy mailcow config
  template:
    dest:  "{{ basedir }}/{{ item }}"
    src: "{{ item }}"
  with_items:
    - docker-compose.yml
  register: config


# Start containers
- name: "stop {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed


- name: "start {{ servicename }} docker"
  docker_compose:
    project_src: "{{ basedir }}"
    state: present

