

services:

  app:

    image: nginx:1-alpine-slim
    restart: always
    volumes:
      - "{{ basedir }}/default.conf:/etc/nginx/conf.d/default.conf:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=8080
    networks:
        - default
        - web

networks:
  web:
    external: true
