---
- name: get secrets from server 1
  slurp: src={{ item }}
  with_items:
    - /data/prometheus/pushover_user_key
    - /data/prometheus/pushover_token
  register: prometheus_secrets

- name: get secrets from server 2
  set_fact: 
    pushover_user_key: "{{ prometheus_secrets.results | selectattr('item', 'equalto', '/data/prometheus/pushover_user_key') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 
    pushover_token: "{{ prometheus_secrets.results | selectattr('item', 'equalto', '/data/prometheus/pushover_token') | map(attribute='content') | list | first | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for prometheus
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/data/prometheus/"
    - "/data/prometheus/config/"
    - "/data/prometheus/data/"
    - "/data/prometheus/alert-data/"

- name: create config files
  template: src={{ item }} dest=/data/prometheus/config/{{ item }}
  with_items: 
    - alertmanager.yml
    - prometheus.yml
    - prometheus.rules
  register: config

- name: start prometheus blackbox-exporter docker
  docker_container: 
    name: prometheus-blackbox-exporter
    image: prom/blackbox-exporter:v0.5.0
    state: started
    restart_policy: always
    ports:
      - 0.0.0.0:9115:9115

- name: start prometheus snmp-exporter docker
  docker_container: 
    name: prometheus-snmp-exporter
    image: prom/snmp-exporter:v0.4.0
    state: started
    restart_policy: always
    ports:
      - 0.0.0.0:9116:9116

- name: stop prometheus-alertmanager docker
  docker_container: 
    name: prometheus-alert
    state: absent
  when: config.changed

- name: start prometheus-alertmanager docker
  docker_container: 
    name: prometheus-alert
    image: prom/alertmanager:v0.7.1
    state: started
    restart_policy: always
    volumes:
      - /data/prometheus/config/alertmanager.yml/:/etc/alertmanager/config.yml
      - /data/prometheus/alert-data/:/alertmanager
    ports:
      - 0.0.0.0:9093:9093

- name: stop prometheus docker
  docker_container: 
    name: prometheus-app
    state: absent
  when: config.changed

- name: start prometheus docker
  docker_container: 
    name: prometheus-app
    image: prom/prometheus:v1.7.1
    state: started
    restart_policy: always
    volumes:
      - /data/prometheus/config/prometheus.yml/:/etc/prometheus/prometheus.yml
      - /data/prometheus/config/prometheus.rules/:/etc/prometheus/prometheus.rules
      - /data/prometheus/data/:/prometheus
    ports:
      - 0.0.0.0:9090:9090
    links:
      - prometheus-blackbox-exporter:blackbox-exporter
      - prometheus-snmp-exporter:snmp-exporter
      - prometheus-alert:alertmanager

