version: "3"

services:

  sysmon:

    image: influxdb:1.5.3
    restart: always
    ports:
      - 0.0.0.0:18086:8086
    volumes:
      - /srv/influx/sysmon/:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "{{influxdb_sysmon.db}}"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "{{ influx_admin_pw }}"
      INFLUXDB_USER: "{{influxdb_sysmon.user}}"
      INFLUXDB_USER_PASSWORD: "{{influxdb_sysmon.password}}"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"

  sysmonproxy:

    image: telegraf:1.7
    restart: always
    ports:
      - 0.0.0.0:18186:8186
      - 0.0.0.0:19273:9273
    volumes:
      - /srv/influx/sysmonproxy.conf:/etc/telegraf/telegraf.conf:ro  

  