---
- name: create folder struct for nodered
  file: 
    path: "/data/nodered/data/" 
    state: "directory"  
     
- name: start nodered docker
  docker_container: 
    name: nodered-app
    image: nodered/node-red-docker:0.16.2
    state: started
    restart_policy: always
    volumes:
      - /data/nodered/data/:/data
    ports:
      - 127.0.0.1:42006:1880
