version: "3"

services:

  app:

    image: pihole/pihole:v5.1.2
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080/tcp"
    volumes:
        - "{{ basedir }}/etc-pihole/:/etc/pihole/"
        - "{{ basedir }}/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "{{ pihole_admin_pass }}"
      DNS1: "{{ hostvars['webserver1']['int_ip4'] }}"
      DNS2: "{{ hostvars['webserver2']['int_ip4'] }}"
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "false"
      CONDITIONAL_FORWARDING: "true"
      CONDITIONAL_FORWARDING_IP: "10.5.0.254"
      CONDITIONAL_FORWARDING_DOMAIN: "lan"
      CONDITIONAL_FORWARDING_REVERSE: "0.5.10.in-addr.arpa"
      WEB_PORT: "{{ web_port }}"

