version: "2.4"

services:

  app:

    image: pihole/pihole:2022.01.1
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "{{ web_port }}:{{ web_port }}/tcp"
    volumes:
        - "{{ basedir }}/etc-pihole/:/etc/pihole/"
        - "{{ basedir }}/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "{{ pihole_admin_pass }}"
      DNSSEC: "true"
      DNSMASQ_LISTENING: "all"
      DHCP_ACTIVE: "false"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "false"
      PIHOLE_DNS_: "{{ hostvars['webserver1'].int_ip4 }};{{ hostvars['webserver2'].int_ip4 }}"
      QUERY_LOGGING: "true"
      WEB_PORT: "{{ web_port }}"
      ServerIP: "{{ ansible_facts['ens18']['ipv4']['address'] }}"
      ServerIPv6: "{{ ansible_facts['ens18']['ipv6'][0]['address'] }}"

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # must be a ULA range
        - subnet: fd00:dead:beef:53::/64
