version: "2.4"

services:

  app:

    image: pihole/pihole:v5.6
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "{{ web_port }}:{{ web_port }}/tcp"
    volumes:
        - "{{ basedir }}/etc-pihole/:/etc/pihole/"
        - "{{ basedir }}/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "{{ pihole_admin_pass }}"
      DNSSEC: "true"
      DNSMASQ_LISTENING: "all"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "false"
      WEB_PORT: "{{ web_port }}"
      ServerIPv6: "fd00:dead:beef:53::2"

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # must be a ULA range
        - subnet: fd00:dead:beef:53::/64
