---

- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: /srv/keycloak/keycloak_admin_pass,  length: 24 }
   - { path: /srv/keycloak/postgres_user_pass,  length: 12 }


- name: create folder struct for keycloak
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /srv/keycloak/
    - /srv/keycloak/db/


- name: Konfig-Dateien erstellen
  template:
    src: "{{ item }}"
    dest: "/srv/keycloak/{{ item }}"
  with_items:
    - docker-compose.yml

- name: start keycloak docker
  docker_service:
    project_src: /srv/keycloak/
    state: present
